v170226   -v071225

In [2]:
import pandas as pd
import numpy as np

print("✅ Pandas instalado!")
print("Versión:", pd.__version__)
print("✅ NumPy instalado!")
print("Versión:", np.__version__)

✅ Pandas instalado!
Versión: 3.0.0
✅ NumPy instalado!
Versión: 2.4.2

In [ ]:
# Una Series de pandas es el equivalente a un vector unidimensional con etiquetas (índice).
vector = np.array([10,20,30])
serie = pd.Series(vector, index=['a','b','c'])
print(serie) # dtype: int64

# Nota: La Serie de pandas tiene un índice (a, b, c) que etiqueta cada elemento del vector. El dtype es int64 porque todos los elementos son enteros. Si mezclamos tipos de datos, el dtype se convierte en object, lo que indica que la Serie puede contener cualquier tipo de dato.

serie2 = pd.Series([1, 2, "tres"])
print(serie2)   # ES UN dtype: object DADA LA MEZCLA DE TIPOS DE DATOS (enteros y cadena de texto)
print(type(serie2)) # <class 'pandas.core.series.Series'>

a    10
b    20
c    30
dtype: int64
0       1
1       2
2    tres
dtype: object
<class 'pandas.Series'>

In [15]:
# Crear un DataFrame a partir de un array de NumPy
data = np.array([[1,2,3], [4,5,6], [7,8,9]]) # Array de NumPy con forma (3,3)
dt_from_array = pd.DataFrame(data, columns=['A','B', 'c'])
print(dt_from_array)
print("---"*10)
# Crear un DataFrame a partir de una lista de listas
data = [[1,'Jhon', 22], [2,'Anna', 24], [3,'Mike', 21]] # Lista de listas con forma (3,3)
df_from_list = pd.DataFrame(data, columns = ['ID', 'Name', 'Age'])
print("Dataframe creado a partir de una lista de listas:")
print(df_from_list)

# Crear un DataFrame a partir de un diccionario (orientado a columnas)
data = {'ID': pd.Series([1,2,3]),
        'Name': pd.Series(['Jhon', 'Anna', 'Mike']),
        'Age': pd.Series([22,24,21])}
df_from_series_dict = pd.DataFrame(data)
print("Dataframe creado a partir de un diccionario de Series:")
print(df_from_series_dict)

   A  B  c
0  1  2  3
1  4  5  6
2  7  8  9
------------------------------
Dataframe creado a partir de una lista de listas:
   ID  Name  Age
0   1  Jhon   22
1   2  Anna   24
2   3  Mike   21
Dataframe creado a partir de un diccionario de Series:
   ID  Name  Age
0   1  Jhon   22
1   2  Anna   24
2   3  Mike   21

In [3]:
# Creating a DataFrame from a dictionary (PERO como estructura orientada a columnas)

# Usuarios
data = {'ID': [1,2,3], 'Name': ['Jhon', 'Anna', 'Mike'], 'Age': [22,24,21]}
df_from_dict = pd.DataFrame(data)
print(df_from_dict)

# Empresa de sofware
data = {'Name': ['Alice', 'Bob', 'Charlie', 'David', 'Eve', 'Frank', 'Grace', 'Hannah', 'Ian', 'Jack', 'Kathy', 'Liam', 'Mona', 'Nate', 'Olivia', 'Paul', 'Quinn', 'Rachel', 'Sam', 'Tina','Sonia'],
        'Age': [25, 30, 35, 28, 22, 40, 29, 31, 27, 33, 26, 24, 32, 42, 30, 28, 27, 31, 25, 26, 39],
        'City': ['New York', 'San Francisco', 'Los Angeles', 'Chicago', 'Miami', 'Seattle', 'Boston', 'Denver', 'Austin', 'Houston', 'Philadelphia', 'Phoenix', 'San Diego', 'Dallas', 'Chicago', 'Detroit', 'Columbus', 'Chicago', 'Indianapolis', 'Miami', 'Miami'],
        'Occupation': ['Frontend', 'Designer', 'owner', 'Developer-back', 'Intern', 'Frontend', 'Developer-back', 'Designer', 'Intern', 'Developer-movil', 'Developer-movil', 'sales', 'Developer-lead', 'Intern', 'Manager', 'fullstack', 'sales', 'Intern', 'marketing', 'Manager', 'Developer-back'],
        'Salary': [70000, 80000, 120000, 95000, 40000, 72000, 88000, 60000, 45000, 98000, 91000, 65000, 115000, 42000, 130000, 105000, 68000, 43000, 75000, 125000, 90000],
        'code': [101, 102, 103, 104, 105, 106, 107, 108, 109, 110, 111, 112, 113, 114, 115, 116, 117, 118, 119, 120,121]
        }
df = pd.DataFrame(data)
print(df)
print(f"Type::: {type(df)}")

   ID  Name  Age
0   1  Jhon   22
1   2  Anna   24
2   3  Mike   21
       Name  Age           City       Occupation  Salary  code
0     Alice   25       New York         Frontend   70000   101
1       Bob   30  San Francisco         Designer   80000   102
2   Charlie   35    Los Angeles            owner  120000   103
3     David   28        Chicago   Developer-back   95000   104
4       Eve   22          Miami           Intern   40000   105
5     Frank   40        Seattle         Frontend   72000   106
6     Grace   29         Boston   Developer-back   88000   107
7    Hannah   31         Denver         Designer   60000   108
8       Ian   27         Austin           Intern   45000   109
9      Jack   33        Houston  Developer-movil   98000   110
10    Kathy   26   Philadelphia  Developer-movil   91000   111
11     Liam   24        Phoenix            sales   65000   112
12     Mona   32      San Diego   Developer-lead  115000   113
13     Nate   42         Dallas           Intern   42000   114
14   Olivia   30        Chicago          Manager  130000   115
15     Paul   28        Detroit        fullstack  105000   116
16    Quinn   27       Columbus            sales   68000   117
17   Rachel   31        Chicago           Intern   43000   118
18      Sam   25   Indianapolis        marketing   75000   119
19     Tina   26          Miami          Manager  125000   120
20    Sonia   39          Miami   Developer-back   90000   121
Type::: <class 'pandas.DataFrame'>

In [12]:
# Estructura orientada a columnas
data = {'ID': [1,2,3], 'Name': ['Jhon', 'Anna', 'Mike'], 'Age': [22,24,21]}
df_from_dict = pd.DataFrame(data)
print("Desde un diccionario con estructura orientada a columnas:")
print(df_from_dict)

# Estructura orientada a registros/objetos (como JSON típico)
data = [{'ID': 1, 'Name': 'Jhon', 'Age': 22},
        {'ID': 2, 'Name': 'Anna', 'Age': 24},
        {'ID': 3, 'Name': 'Mike', 'Age': 21}]
# Qué representa
# cada objeto = una fila
# fila → objeto con atributos
# cada objeto contiene todos los atributo
df_from_records = pd.DataFrame(data)
print("Desde una lista de diccionarios (estructura orientada a registros/objetos):")
print(df_from_records)

print("---"*10)
# Convertir un DataFrame a JSON con orientación a registros
print("---DataFrame convertido a JSON con orientación a registros:")
print(df_from_records.to_json(orient="records"))
# Convertir un DataFrame a JSON con orientación a columnas
print("---DataFrame convertido a JSON con orientación a columnas:")
print(df_from_records.to_json(orient="columns"))

Desde un diccionario con estructura orientada a columnas:
   ID  Name  Age
0   1  Jhon   22
1   2  Anna   24
2   3  Mike   21
Desde una lista de diccionarios (estructura orientada a registros/objetos):
   ID  Name  Age
0   1  Jhon   22
1   2  Anna   24
2   3  Mike   21
------------------------------
---DataFrame convertido a JSON con orientación a registros:
[{"ID":1,"Name":"Jhon","Age":22},{"ID":2,"Name":"Anna","Age":24},{"ID":3,"Name":"Mike","Age":21}]
---DataFrame convertido a JSON con orientación a columnas:
{"ID":{"0":1,"1":2,"2":3},"Name":{"0":"Jhon","1":"Anna","2":"Mike"},"Age":{"0":22,"1":24,"2":21}}

In [ ]:
# Convertir diccionario (adicional) a DataFrame
data_additional = {
    'Employee_Code': [101, 102, 103, 104, 105, 106, 107, 108, 109, 110, 111, 112, 113, 114, 115, 116, 117, 118, 119, 120,121],
    'Department': ['IT', 'Design', 'Management', 'IT', 'Internship', 'IT', 'IT', 'Design', 'Internship', 'IT', 'IT', 'Sales', 'IT', 'Internship', 'Management', 'IT', 'Sales', 'Internship', 'Marketing', 'Management','IT'],
}
df_additional = pd.DataFrame(data_additional)
print("DataFrame adicional:")
print(df_additional)

DataFrame adicional:
    Employee_Code  Department
0             101          IT
1             102      Design
2             103  Management
3             104          IT
4             105  Internship
5             106          IT
6             107          IT
7             108      Design
8             109  Internship
9             110          IT
10            111          IT
11            112       Sales
12            113          IT
13            114  Internship
14            115  Management
15            116          IT
16            117       Sales
17            118  Internship
18            119   Marketing
19            120  Management
20            121          IT

In [144]:
# en 'df' pasar la ultima columna 'code' al inicio del DataFrame
cols = df.columns.tolist()
# print(cols) # ['code', 'Name', 'Age', 'City', 'Occupation', 'Salary']
cols = cols[-1:] + cols[:-1]
# ['code'] + ['Name', 'Age', 'City', 'Occupation', 'Salary']
df = df[cols]
# Cuando se pasa una lista de nombres de columnas entre corchetes, pandas devuelve un nuevo DataFrame con las columnas exactamente en ese orden.
print("DataFrame con columna 'code' al inicio:")
print(df)
# df.columns es un índice con los nombres de las columnas.
# .tolist() lo convierte en una lista de Python
# cols[-1:] toma la última columna, 'code'
# y cols[:-1] toma todas las columnas excepto la última.

DataFrame con columna 'code' al inicio:
    code     Name  Age           City       Occupation  Salary
0    101    Alice   25       New York         Frontend   70000
1    102      Bob   30  San Francisco         Designer   80000
2    103  Charlie   35    Los Angeles            owner  120000
3    104    David   28        Chicago   Developer-back   95000
4    105      Eve   22          Miami           Intern   40000
5    106    Frank   40        Seattle         Frontend   72000
6    107    Grace   29         Boston   Developer-back   88000
7    108   Hannah   31         Denver         Designer   60000
8    109      Ian   27         Austin           Intern   45000
9    110     Jack   33        Houston  Developer-movil   98000
10   111    Kathy   26   Philadelphia  Developer-movil   91000
11   112     Liam   24        Phoenix            sales   65000
12   113     Mona   32      San Diego   Developer-lead  115000
13   114     Nate   42         Dallas           Intern   42000
14   115   Olivia   30        Chicago          Manager  130000
15   116     Paul   28        Detroit        fullstack  105000
16   117    Quinn   27       Columbus            sales   68000
17   118   Rachel   31        Chicago           Intern   43000
18   119      Sam   25   Indianapolis        marketing   75000
19   120     Tina   26          Miami          Manager  125000
20   121    Sonia   39          Miami   Developer-back   90000

---

**SELECCIÓN DE DATOS EN PANDAS MEDIANTE `loc`, `iloc` Y NOMBRE DIRECTO**

iloc: Se basa en la posición (número de índice).  
loc: Se basa en las etiquetas de los índices.

In [ ]:
## 1. Selección por POSICIÓN → `iloc`
# Se usa cuando quieres acceder por _índices numéricos_ (0, 1, 2…).
print("---- Fila 0, Columna 2")
print(df.iloc[0, 2])        # Fila 0, Columna 2 #→ 'New York'
print("---- Fila 3 completa")
# Fila 3 completa, presentada de forma tubular
F3= df.iloc[3] # df.iloc[3, :] 
# type(F3)  #→ pandas.core.series.Series
print(F3)
print("---- Columna 'Occupation'")
print(df.iloc[:, 3])    # Toda la columna 3 (Occupation)
print("---- Primeras 5 filas, primeras 3 columnas")
print(df.iloc[0:5, 0:3])  # Primeras 5 filas, primeras 3 columnas
print("---- Primeras 5 filas, columnas 0 y 3")
print(df.iloc[0:5, [0, 3]])
print("---- Filas 0, 5 y 15; Columnas 0, 2 y 3")
print(df.iloc[[0, 5, 15], [0, 2, 3]])  # Filas 0, 2 y 4; Columnas 1 y 3

#NOTA:
# El uso de .iloc es necesario porque elimina toda ambigüedad, obligando a pandas a interpretar los argumentos como posiciones numéricas (enteros) y no como nombres o etiquetas (nota, tambien es posible es uso del metodo .loc el cual se usa para acceder a datos por etiquetas o booleanos).
# Por tanto, la forma df[f][c] puede ser ambigua si las filas o columnas tienen etiquetas numéricas que coinciden con los índices posicionales. (en otras palabras, si una fila o columna se llama '0', ¿estás refiriéndote a la fila/columna con etiqueta '0' o a la primera fila/columna en posición 0? .iloc elimina esta ambigüedad al especificar que siempre se trata de posiciones numéricas.)

---- Fila 0, Columna 2
25
---- Fila 3 completa
code                     104
Name                   David
Age                       28
City                 Chicago
Occupation    Developer-back
Salary                 95000
Name: 3, dtype: object
---- Columna 'Occupation'
0          New York
1     San Francisco
2       Los Angeles
3           Chicago
4             Miami
5           Seattle
6            Boston
7            Denver
8            Austin
9           Houston
10     Philadelphia
11          Phoenix
12        San Diego
13           Dallas
14          Chicago
15          Detroit
16         Columbus
17          Chicago
18     Indianapolis
19            Miami
20            Miami
Name: City, dtype: object
---- Primeras 5 filas, primeras 3 columnas
   code     Name  Age
0   101    Alice   25
1   102      Bob   30
2   103  Charlie   35
3   104    David   28
4   105      Eve   22
---- Primeras 5 filas, columnas 0 y 3
   code           City
0   101       New York
1   102  San Francisco
2   103    Los Angeles
3   104        Chicago
4   105          Miami
---- Filas 0, 5 y 15; Columnas 0, 2 y 3
    code  Age      City
0    101   25  New York
5    106   40   Seattle
15   116   28   Detroit

In [16]:
# 2. Selección por ETIQUETA → `loc`
# Se usa cuando quieres acceder por _nombres de filas o columnas_ (etiquetas).
# El primer argumento de .loc se refiere a las filas (etiquetas de índice) y el segundo a las columnas (nombres de columnas).
# loc[] no solo acepta números, también recibe rangos, etiquetas, listas o una lista de condiciones booleanas para seleccionar filas.

# Uso de 'rangos' para seleccionar filas por etiqueta
name_city_occupation_column = df.loc[:,['Name','City', 'Occupation']]
print(" --- DataFrame con columnas 'Name', 'City' y 'Occupation':")
display(name_city_occupation_column)

# uso de 'condiciones booleanas' para seleccionar filas por etiqueta
print(" --- Filas donde la ciudad es 'Chicago' y no sea 'Intern':")
mascara_chicago = df['City'] == 'Chicago' # Esto devuelve una Serie de booleanos (True/False) indicando qué filas cumplen
display(df.loc[mascara_chicago, ['Name', 'City', 'Occupation']])

# Seleccionar filas por etiqueta usando una lista de etiquetas
print(" --- Filas con etiquetas 0, 2 y 5:")
display(df.loc[[0, 2, 5]])

print(" --- Filas donde la edad es mayor a 35:")
display(df.loc[df["Age"] > 35, :])  # filas que cumplen condición

 --- DataFrame con columnas 'Name', 'City' y 'Occupation':

       Name           City       Occupation
0     Alice       New York         Frontend
1       Bob  San Francisco         Designer
2   Charlie    Los Angeles            owner
3     David        Chicago   Developer-back
4       Eve          Miami           Intern
5     Frank        Seattle         Frontend
6     Grace         Boston   Developer-back
7    Hannah         Denver         Designer
8       Ian         Austin           Intern
9      Jack        Houston  Developer-movil
10    Kathy   Philadelphia  Developer-movil
11     Liam        Phoenix            sales
12     Mona      San Diego   Developer-lead
13     Nate         Dallas           Intern
14   Olivia        Chicago          Manager
15     Paul        Detroit        fullstack
16    Quinn       Columbus            sales
17   Rachel        Chicago           Intern
18      Sam   Indianapolis        marketing
19     Tina          Miami          Manager
20    Sonia          Miami   Developer-back

 --- Filas donde la ciudad es 'Chicago' y no sea 'Intern':

      Name     City      Occupation
3    David  Chicago  Developer-back
14  Olivia  Chicago         Manager
17  Rachel  Chicago          Intern

 --- Filas con etiquetas 0, 2 y 5:

      Name  Age         City Occupation  Salary  code
0    Alice   25     New York   Frontend   70000   101
2  Charlie   35  Los Angeles      owner  120000   103
5    Frank   40      Seattle   Frontend   72000   106

 --- Filas donde la edad es mayor a 35:

     Name  Age     City      Occupation  Salary  code
5   Frank   40  Seattle        Frontend   72000   106
13   Nate   42   Dallas          Intern   42000   114
20  Sonia   39    Miami  Developer-back   90000   121

In [ ]:
## 2. Selección por ETIQUERA  → `loc`
# Se usa cuando quieres acceder por _etiquetas de fila y/o columna.
print("---- Fila 0, Columna 'City': ")
print(df.loc[0, "City"])        # Fila 0, Columna 'City' #→ 'New York'

# Fila 4 completa, presentada de forma tubular?
print("---- Fila 4 completa")
F3 = df.loc[3]  # df.loc[3, :]  # Recordar que la primera fila tiene indice 0
# Nota en algunos diccionarios los indices pueden ser cadenas de texto
# type(F3)  #→ pandas.core.series.Series
print(F3)
print("---- Columna 'Occupation'")
print(df.loc[:, "Occupation"])    # Toda la columna 3 (Occupation)
print("---- Primeras 5 filas, primeras 3 columnas")
print(df.loc[0:4, ["Name", "Age", "City"]])
print("---- Primeras 5 filas, columnas 0 y 3")
print(df.loc[0:4, ["Name", "Occupation"]])
print("---- Filas 0, 5 y 15; Columnas 0, 2 y 3")
print(df.loc[[0, 5, 15], ["Name", "City", "Occupation"]])  # Filas 0, 2 y 4; Columnas 1 y 3

---- Fila 0, Columna 'City':
New York
---- Fila 3 completa
Name                   David
Age                       28
City                 Chicago
Occupation    Developer-back
Salary                 95000
code                     104
Name: 3, dtype: object
---- Columna 'Occupation'
0            Frontend
1            Designer
2               owner
3      Developer-back
4              Intern
5            Frontend
6      Developer-back
7            Designer
8              Intern
9     Developer-movil
10    Developer-movil
11              sales
12     Developer-lead
13             Intern
14            Manager
15          fullstack
16              sales
17             Intern
18          marketing
19            Manager
20     Developer-back
Name: Occupation, dtype: str
---- Primeras 5 filas, primeras 3 columnas
      Name  Age           City
0    Alice   25       New York
1      Bob   30  San Francisco
2  Charlie   35    Los Angeles
3    David   28        Chicago
4      Eve   22          Miami
---- Primeras 5 filas, columnas 0 y 3
      Name      Occupation
0    Alice        Frontend
1      Bob        Designer
2  Charlie           owner
3    David  Developer-back
4      Eve          Intern
---- Filas 0, 5 y 15; Columnas 0, 2 y 3
     Name      City Occupation
0   Alice  New York   Frontend
5   Frank   Seattle   Frontend
15   Paul   Detroit  fullstack

In [147]:
# df[...] está diseñado para aceptar distintos tipos de argumentos, y pandas decide qué hacer según el tipo de ese argumento.
# df["Name"] → una sola etiqueta de columna → devuelve una Series con esa columna. (selección simple)
# df[["Name", "Occupation"]] → lista de etiquetas de columna → devuelve un DataFrame con esas columnas.
# df[mask_booleana] → una máscara booleana → devuelve un DataFrame filtrado según la máscara.
### df[mask][['col1', 'col2']] // Indexación directa

In [148]:
# 3. Selección simple por NOMBRE DIRECTO (solo columna) parte1
# Se usa cuando quieres acceder por _nombres de columna_ directamente.
### Para obtener **Series** (una sola columna) uso de corchetes simples `[]`
### NOTA: Para obtener **DataFrame** (varias columnas) uso de corchetes dobles

##### output: SERIES
print("---- Columna 'City' directamente")
print(df["City"])    # Toda la columna 'City'
print(type(df["City"]))  #→ pandas.core.series.Series
##### output: DATAFRAME
print("---- Columna 'City' directamente como DataFrame (con cabecera)")
print(df[["City"]])    # Toda la columna 'City'
print(type(df[["City"]]))  #→ pandas.core.frame.DataFrame

---- Columna 'City' directamente
0          New York
1     San Francisco
2       Los Angeles
3           Chicago
4             Miami
5           Seattle
6            Boston
7            Denver
8            Austin
9           Houston
10     Philadelphia
11          Phoenix
12        San Diego
13           Dallas
14          Chicago
15          Detroit
16         Columbus
17          Chicago
18     Indianapolis
19            Miami
20            Miami
Name: City, dtype: object
<class 'pandas.core.series.Series'>
---- Columna 'City' directamente como DataFrame (con cabecera)
             City
0        New York
1   San Francisco
2     Los Angeles
3         Chicago
4           Miami
5         Seattle
6          Boston
7          Denver
8          Austin
9         Houston
10   Philadelphia
11        Phoenix
12      San Diego
13         Dallas
14        Chicago
15        Detroit
16       Columbus
17        Chicago
18   Indianapolis
19          Miami
20          Miami
<class 'pandas.core.frame.DataFrame'>

In [149]:
# La selección simple por NOMBRE DIRECTO permite filtrar filas basadas en condiciones específicas aplicadas a las columnas del DataFrame.
# Esto se logra creando máscaras booleanas que representan las condiciones deseadas y luego aplicándolas al DataFrame para obtener un subconjunto filtrado.
### Ejemplo 1
print(df[df['Age'] >= 39])  # Rows where Age >= 39
print("-----------------------------------------")

### Ejemplo 2 - Múltiples condiciones:
# 1. condición 2: Filtrar por edad mayor a 28
condicion_edad = df['Age'] >= 28
# 2. condición 1: Filtrar por ciudades 'Chicago' o 'Miami'
condicion_ciudades = (df['City'] == 'Chicago') | (df['City'] == 'Miami')
# 3. condición 3: Filtrar por ocupación 'Intern' o 'Developer 
condicion_ocupacion = (df['Occupation'] == 'Intern') | (df['Occupation'] == 'Developer')
# 4. Combina las tres condiciones con AND (&)
# (Ciudades Y Edad Y Ocupación)
resultado = df[condicion_ciudades & condicion_edad & condicion_ocupacion][['Name', 'City', 'Occupation']]
print(resultado)
type(resultado)  #→ pandas.core.frame.DataFrame

    code   Name  Age     City      Occupation  Salary
5    106  Frank   40  Seattle        Frontend   72000
13   114   Nate   42   Dallas          Intern   42000
20   121  Sonia   39    Miami  Developer-back   90000
-----------------------------------------
      Name     City Occupation
17  Rachel  Chicago     Intern

pandas.core.frame.DataFrame

In [150]:
# 3. Selección por lista de NOMBRES DIRECTOS (solo columnas) parte2
# Se usa cuando quieres acceder por _nombres de columna_ directamente.
### Para obtener **DataFrame** (varias columnas) uso de corchetes dobles
### NOTA: Para obtener **Series** (una sola columna) uso de corchetes simples `[]`
##### output: DataFrame
#print(df[['Name']])  # Select specific columns (retorna un DataFrame y no una Serie)
print("----DataFrame de 2 columnas----")
print(df[["Name", "Occupation"]])  # Columnas 'Name' y 'Occupation'
# equivalente a: df.loc[:, ["Name", "Occupation"]]
# usa el operador de indexación del DataFrame y solo permite seleccionar columnas por nombre cuando se pasa una lista.
#////
# NOTA: para seleccionar a la vez filas y columnas por sus “dos ejes” en la forma df[filas, columnas] se requiere usar uno de los indexadores, iloc o loc, o bien una variante equivalente como df.where o boolean indexing, pero ya no sirve la sintaxis simple df[...] de una sola dimensión.

----DataFrame de 2 columnas----
       Name       Occupation
0     Alice         Frontend
1       Bob         Designer
2   Charlie            owner
3     David   Developer-back
4       Eve           Intern
5     Frank         Frontend
6     Grace   Developer-back
7    Hannah         Designer
8       Ian           Intern
9      Jack  Developer-movil
10    Kathy  Developer-movil
11     Liam            sales
12     Mona   Developer-lead
13     Nate           Intern
14   Olivia          Manager
15     Paul        fullstack
16    Quinn            sales
17   Rachel           Intern
18      Sam        marketing
19     Tina          Manager
20    Sonia   Developer-back

### Selección avanzada ####

In [151]:
# 🟣 4. Selección avanzada
### ✔ Indexación directa - df[mask][['col1', 'col2']]
### De la forma:
# mascara_booleana = (condicion1) & (condicion2)
# df_filtrado = df[mascara_booleana][["columna"]]
# ----
# print(df[df['Age'] > 28])  # Rows where Age > 28
# print(df[(df['Age'] > 28) & (df['City'] == 'Chicago')])  # Multiple conditions
df[(df['Age'] > 28) & ((df['City'] == 'Chicago') | (df['City'] == 'Miami'))][['Name', 'City', 'Occupation']]
# nota: el operador & representa "AND" y el operador | representa "OR" en pandas.
# nota: la expresion [['Name', 'City', 'Occupation']] se utiliza para seleccionar múltiples columnas específicas del DataFrame resultante después de aplicar las condiciones de filtrado.
# nota: si no se incluye esta parte, el resultado incluirá todos lo campos(columnas) del DataFrame original para las filas que cumplen las condiciones de filtrado.

      Name     City      Occupation
14  Olivia  Chicago         Manager
17  Rachel  Chicago          Intern
20   Sonia    Miami  Developer-back

In [152]:

##### CON 3 CONDICIONES #####
condicion_edad = df['Age'] > 28
condicion_ciudades = (df['City'] == 'Chicago') | (df['City'] == 'Miami')
condicion_ocupation = df['Occupation'] == 'Developer-back'
df[condicion_edad & condicion_ciudades & condicion_ocupation][['Name', 'City', 'Occupation']]

     Name   City      Occupation
20  Sonia  Miami  Developer-back

In [153]:
# 🟣 4. Selección avanzada
### ✔ Usar `isin`
# 'isin' permite filtrar filas según si una columna tiene valores dentro de una lista dada.
# En Excel es similar a: aplicar Filtro a la tabla por varios valores,
# o usar funciones como OR() y COUNTIF() para comprobar si un valor está en una lista.
#### CON 1 CONDICIÓN #####
print(df[df['City'].isin(['Chicago', 'Miami'])]) 
# Dataframe, con las filas que tengas comoCities Chicago or Miami

    code    Name  Age     City      Occupation  Salary
3    104   David   28  Chicago  Developer-back   95000
4    105     Eve   22    Miami          Intern   40000
14   115  Olivia   30  Chicago         Manager  130000
17   118  Rachel   31  Chicago          Intern   43000
19   120    Tina   26    Miami         Manager  125000
20   121   Sonia   39    Miami  Developer-back   90000

In [154]:
##### CON 2 CONDICIONES ##### (Es posible indicar que columnas incluir en el resultado)
# 1. Crea la condición de Ciudades usando .isin()
condicion_ciudades = df['City'].isin(['Chicago', 'Miami'])
# 2. Crea la condición de Edad
condicion_edad = df['Age'] > 28
# 3. Combina y aplica las condiciones
df[condicion_ciudades & condicion_edad][['Name', 'City', 'Occupation']]

      Name     City      Occupation
14  Olivia  Chicago         Manager
17  Rachel  Chicago          Intern
20   Sonia    Miami  Developer-back

In [155]:
##### CON 3 CONDICIONES #####
# 1. Condición de Ciudades (OR)
condicion_ciudades = df['City'].isin(['Chicago', 'Miami'])
# 2. Condición de Edad (AND)
condicion_edad = df['Age'] > 28
# 3. Condición de Ocupación (AND)
condicion_ocupacion = df['Occupation'] == 'Developer-back' # Nueva condición
# 4. Combina las tres condiciones con AND (&)
# (Ciudades Y Edad Y Ocupación)
resultado = df[condicion_ciudades & condicion_edad & condicion_ocupacion][['Name', 'City', 'Occupation']]
print(resultado)
type(resultado)  #→ pandas.core.frame.DataFrame

     Name   City      Occupation
20  Sonia  Miami  Developer-back

pandas.core.frame.DataFrame

In [156]:
# 🟣 4. Selección avanzada
### ✔ Selección por query
### (filtrado con query o filtrado con expresión tipo SQL.)
# todas las columnas de los registros filtrados
# print(df.query("Age > 28 and City == 'Chicago'"))
# solo la columna name y city de los registros filtrados
# df.query("Age > 28 and City == 'Chicago'")[['Name', 'City', 'Occupation']]
df.query("Age > 28 and (City == 'Chicago' or City == 'Miami')")[['Name', 'City', 'Occupation']]

      Name     City      Occupation
14  Olivia  Chicago         Manager
17  Rachel  Chicago          Intern
20   Sonia    Miami  Developer-back

In [157]:
resultado = df.query(
    "(City == 'Chicago' or City == 'Miami')"
    " and Age > 28"
    " and Occupation == 'Developer-back'"
)[['Name', 'City', 'Occupation']]
print(resultado)

     Name   City      Occupation
20  Sonia  Miami  Developer-back

In [158]:
# 🟣 4. Selección avanzada
### ✔ loc con máscara booleana
##### CON 2 CONDICIONES #####
# Using .loc for label-based indexing with multiple conditions (forma Logica)
df.loc[(df['Age'] > 28) & (df['City'].isin(['Chicago', 'Miami'])), ['Name', 'City', 'Occupation']]
# nota: el operador & se usa para AND, y el operador | se usa para OR

      Name     City      Occupation
14  Olivia  Chicago         Manager
17  Rachel  Chicago          Intern
20   Sonia    Miami  Developer-back

In [159]:
#-----------------------------------------
#-----------------------------------------
#-----------------------------------------
#-----------------------------------------

In [160]:
# 5. Selección por RANGO de filas (slicing)
# Selección por rango de filas usando slicing (similar a listas de Python)

print(df[1:3]) # Select specific rows
# df[1:3] es equivalente a df.iloc[1:3, :]
# Es posible indicar que columnas incluir en el resultado:
# print(df[1:3][['Name', 'City']])

   code     Name  Age           City Occupation  Salary
1   102      Bob   30  San Francisco   Designer   80000
2   103  Charlie   35    Los Angeles      owner  120000

In [161]:
#Use the unique method to determine the unique elements in a column of a DataFrame.
unique_dates = df['Age'].unique()
print(unique_dates)
print("-----"*7)
unique_occupations = df['Occupation'].unique()
print(unique_occupations)
print("-----"*7)
unique_cities = df['City'].unique()
print(unique_cities)
print("-----"*7)
#Cuantas ciudades únicas hay?
# Devuelve el número de valores distintos, excluyendo NaN por defecto.
num_unique_cities = df['City'].nunique()
print(f"Número de ciudades únicas: {num_unique_cities}") # Número de ciudades únicas: 17
#Cuantas filas hay en la columna City?
num_total_cities = len(df['City'])
print(f"Número total de filas en la columna 'City': {num_total_cities}")
# Devuelve el número total de filas en esa columna, incluidas las que tienen NaN. No sirve para contar valores distintos, solo cuenta cuántos registros hay.
# Cuantas ciudades únicas hay? otra forma (puede incluir el valor NaN si existe):
num_unique_cities_with_nan = len(df['City'].unique())
print(f"Número de ciudades únicas (incluyendo NaN si existe): {num_unique_cities_with_nan}")

[25 30 35 28 22 40 29 31 27 33 26 24 32 42 39]
-----------------------------------
['Frontend' 'Designer' 'owner' 'Developer-back' 'Intern' 'Developer-movil'
 'sales' 'Developer-lead' 'Manager' 'fullstack' 'marketing']
-----------------------------------
['New York' 'San Francisco' 'Los Angeles' 'Chicago' 'Miami' 'Seattle'
 'Boston' 'Denver' 'Austin' 'Houston' 'Philadelphia' 'Phoenix' 'San Diego'
 'Dallas' 'Detroit' 'Columbus' 'Indianapolis']
-----------------------------------
Número de ciudades únicas: 17
Número total de filas en la columna 'City': 21
Número de ciudades únicas (incluyendo NaN si existe): 17

In [162]:
# 'Conteo de ocurrencias' de cada ciudad
city_counts = df['City'].value_counts()
print("Conteo de ocurrencias de cada ciudad:")
print(city_counts)

Conteo de ocurrencias de cada ciudad:
City
Miami            3
Chicago          3
New York         1
Los Angeles      1
San Francisco    1
Seattle          1
Boston           1
Denver           1
Austin           1
Houston          1
Philadelphia     1
Phoenix          1
San Diego        1
Dallas           1
Detroit          1
Columbus         1
Indianapolis     1
Name: count, dtype: int64

In [163]:
# 'Conteo de ocurrencias' de cada ocupación
occupation_counts = df['Occupation'].value_counts()
print("Conteo de ocurrencias de cada ocupación:")
print(occupation_counts)

Conteo de ocurrencias de cada ocupación:
Occupation
Intern             4
Developer-back     3
Frontend           2
Manager            2
Designer           2
Developer-movil    2
sales              2
owner              1
Developer-lead     1
fullstack          1
marketing          1
Name: count, dtype: int64

In [164]:
# Ordenar (devuelve DataFrame)
df.sort_values(by='Age', ascending=False)[['Name', 'Age']]

       Name  Age
13     Nate   42
5     Frank   40
20    Sonia   39
2   Charlie   35
9      Jack   33
12     Mona   32
17   Rachel   31
7    Hannah   31
1       Bob   30
14   Olivia   30
6     Grace   29
3     David   28
15     Paul   28
8       Ian   27
16    Quinn   27
19     Tina   26
10    Kathy   26
18      Sam   25
0     Alice   25
11     Liam   24
4       Eve   22

In [165]:
# df.shape devuelve las dimensiones del DataFrame como una tupla (n_filas, n_columnas)
# df.shape → devuelve algo como (n_filas, n_columnas).
# df.shape[0] → toma el primer elemento de la tupla, es decir, el número de filas.
# df.shape[1] → toma el segundo elemento, el número de columnas.
print(df.shape)  #→ (21, 5)
print(df.shape[0])  #→ 21 (Hay 21 registros/filas)
print(df.shape[1])  #→ 5 (Hay 5 columnas)

(21, 6)
21
6

In [166]:
# Descripción estadística básica del DataFrame
description = df.describe()
print("Descripción estadística básica del DataFrame:")
print(description)

Descripción estadística básica del DataFrame:
             code        Age         Salary
count   21.000000  21.000000      21.000000
mean   111.000000  30.000000   81761.904762
std      6.204837   5.357238   27694.592905
min    101.000000  22.000000   40000.000000
25%    106.000000  26.000000   65000.000000
50%    111.000000  29.000000   80000.000000
75%    116.000000  32.000000   98000.000000
max    121.000000  42.000000  130000.000000

In [167]:
# Suma de salarios totales, con formato de decimales y separadores de miles
total_salary = df['Salary'].sum()
print(f"Suma total de salarios: {total_salary:,.2f}")
# (usa la coma para miles y el punto para decimales)

print("-----"*7)
# promedio entre todos los empleados
average_salary = df['Salary'].mean()
# .mean() calcula el promedio aritmético de los valores en la columna 'Salary'.
# los valores NaN se ignoran automáticamente en el cálculo del promedio.
print(f"Salario promedio: {average_salary:,.2f} (21 empleados)")

print("-----"*7)
# Minimo y máximo salario
min_salary = df['Salary'].min()
max_salary = df['Salary'].max()
print(f"Salario mínimo: {min_salary:,.2f}")
print(f"Salario máximo: {max_salary:,.2f}")

print("-----"*7)
# Mediana del salario
# Ma mediana es el valor que separa la mitad superior de la mitad inferior de un conjunto de datos.
# Si el número de observaciones es impar, la mediana es el valor central.
# Si es par, la mediana es el promedio de los dos valores centrales.
median_salary = df['Salary'].median()
print(f"Mediana del salario: {median_salary:,.2f}")

Suma total de salarios: 1,717,000.00
-----------------------------------
Salario promedio: 81,761.90 (21 empleados)
-----------------------------------
Salario mínimo: 40,000.00
Salario máximo: 130,000.00
-----------------------------------
Mediana del salario: 80,000.00

In [168]:
# Media de salario por ocupación
mean_salary_by_occupation = df.groupby('Occupation')['Salary'].mean()
print("Media de salario por ocupación:")
print(mean_salary_by_occupation)

Media de salario por ocupación:
Occupation
Designer            70000.0
Developer-back      91000.0
Developer-lead     115000.0
Developer-movil     94500.0
Frontend            71000.0
Intern              42500.0
Manager            127500.0
fullstack          105000.0
marketing           75000.0
owner              120000.0
sales               66500.0
Name: Salary, dtype: float64

In [169]:
# Ejemplo de Agrupamiento (GroupBy) con múltiples agregados (calcular agregados)
# De la forma df.groupby('categoria').agg({'monto':'sum', 'precio':'mean'})

df_copy = df.copy() # buena práctica.
# Aunque es posible no se usará diccionario explícito, sino argumentos nombrados (keyword arguments):
# df_grouped = df_copy.groupby('Occupation').agg(
#     Average_Salary=('Salary', 'mean'), # Sintaxis con argumentos nombrados
#     Total_Salary=('Salary', 'sum'),
#     Employee_Count=('Salary', 'count'),
# )
# #pero se recomienda en dos pasos el agrupamiento y el renombre:
df_grouped = df_copy.groupby('Occupation')['Salary'].agg(['mean', 'sum', 'count'])
df_grouped = df_grouped.rename(columns={'mean': 'Average_Salary', 'sum': 'Total_Salary', 'count': 'Employee_Count'})
print("Agrupado por Ocupación con agregados de Salario:")
print(df_grouped)

# Sobre: df_copy.groupby('Occupation')
# Se “parte” el DataFrame en grupos según el valor de la columna Occupation.
# Cada grupo contiene todas las filas que comparten el mismo valor de ocupación.
# ['Salary']
# De esos grupos se toma solo la columna numérica Salary, porque sobre ella se van a calcular agregados.
# El resultado es un objeto GroupBy de la serie Salary por cada ocupación.
# .agg(['mean', 'sum', 'count'])
# agg aplica varias funciones de agregación a la vez sobre cada grupo.
# mean: salario promedio de la ocupación.
# sum: suma total de salarios de esa ocupación.
# count: cuántos registros (empleados) tienen salario en esa ocupación.

Agrupado por Ocupación con agregados de Salario:
                 Average_Salary  Total_Salary  Employee_Count
Occupation
Designer                70000.0        140000               2
Developer-back          91000.0        273000               3
Developer-lead         115000.0        115000               1
Developer-movil         94500.0        189000               2
Frontend                71000.0        142000               2
Intern                  42500.0        170000               4
Manager                127500.0        255000               2
fullstack              105000.0        105000               1
marketing               75000.0         75000               1
owner                  120000.0        120000               1
sales                   66500.0        133000               2

In [170]:
# Ejemplo avanzado de selección y agrupamiento con Encadenamiento de métodos.
df[df["Age"] > 28].groupby("Occupation")["Salary"].mean().sort_values(ascending=False)
# 1. Máscara booleana de registros >28
# 2. Agrupa ese subconjunto por Occupation y selecciona la columna Salary dentro de cada grupo.
# 3. Calcula el salario promedio dentro de cada ocupación (sobre los empleados ya filtrados por edad).
# 4. Ordena las ocupaciones de mayor a menor salario promedio

Occupation
Manager            130000.0
owner              120000.0
Developer-lead     115000.0
Developer-movil     98000.0
Developer-back      89000.0
Frontend            72000.0
Designer            70000.0
Intern              42500.0
Name: Salary, dtype: float64

In [171]:
# Resetear el índice del DataFrame después de filtrar filas
# Ese código se usa para “limpiar” el índice después de filtrar, para que el nuevo DataFrame tenga un índice consecutivo empezando en 0, sin huecos.
filtered_df = df[df['Age'] >= 39].reset_index(drop=True)
print("DataFrame filtrado (con índice reseteado):")
print(filtered_df)
# No toma los índices antiguos del DataFrame original (que era 5 Frank, 13 Nate, 20 Sonia)
# -------------
print("-------------------------------------------")
print("Pero NO se ha modificado el DataFrame original:")
print(df.head(6))

DataFrame filtrado (con índice reseteado):
   code   Name  Age     City      Occupation  Salary
0   106  Frank   40  Seattle        Frontend   72000
1   114   Nate   42   Dallas          Intern   42000
2   121  Sonia   39    Miami  Developer-back   90000
-------------------------------------------
Pero NO se ha modificado el DataFrame original:
   code     Name  Age           City      Occupation  Salary
0   101    Alice   25       New York        Frontend   70000
1   102      Bob   30  San Francisco        Designer   80000
2   103  Charlie   35    Los Angeles           owner  120000
3   104    David   28        Chicago  Developer-back   95000
4   105      Eve   22          Miami          Intern   40000
5   106    Frank   40        Seattle        Frontend   72000

In [172]:
# Renombrar columnas # SE APLICA AL DATAFRAME ORIGINAL
df.rename(columns={'Name': 'Employee', 'Age': 'Employee_Age', 'Salary': 'monthly_salary', 'code': 'Employee_Code'}, inplace=True)
# Mostrar los 6 primeros registros con las nuevas columnas
print(df.head(6))

   Employee_Code Employee  Employee_Age           City      Occupation  \
0            101    Alice            25       New York        Frontend
1            102      Bob            30  San Francisco        Designer
2            103  Charlie            35    Los Angeles           owner
3            104    David            28        Chicago  Developer-back
4            105      Eve            22          Miami          Intern
5            106    Frank            40        Seattle        Frontend

   monthly_salary
0           70000
1           80000
2          120000
3           95000
4           40000
5           72000

In [173]:
# Eliminar columnas
# ERROR # df_new = df.drop(columns=['City', 'Job Title'], inplace=True).reset_index(drop=True) # ERROR
df_new = df.drop(columns=['City', 'Occupation']).reset_index(drop=True)
print("DataFrame después de eliminar columnas 'City' y 'Occupation':")
print(df_new)

DataFrame después de eliminar columnas 'City' y 'Occupation':
    Employee_Code Employee  Employee_Age  monthly_salary
0             101    Alice            25           70000
1             102      Bob            30           80000
2             103  Charlie            35          120000
3             104    David            28           95000
4             105      Eve            22           40000
5             106    Frank            40           72000
6             107    Grace            29           88000
7             108   Hannah            31           60000
8             109      Ian            27           45000
9             110     Jack            33           98000
10            111    Kathy            26           91000
11            112     Liam            24           65000
12            113     Mona            32          115000
13            114     Nate            42           42000
14            115   Olivia            30          130000
15            116     Paul            28          105000
16            117    Quinn            27           68000
17            118   Rachel            31           43000
18            119      Sam            25           75000
19            120     Tina            26          125000
20            121    Sonia            39           90000

In [174]:
# Agregar una nueva columna 'Annual_Salary' que es el salario mensual multiplicado por 12
df['Annual_Salary'] = df['monthly_salary'] * 12
print("DataFrame con nueva columna 'Annual_Salary':")
print(df)

DataFrame con nueva columna 'Annual_Salary':
    Employee_Code Employee  Employee_Age           City       Occupation  \
0             101    Alice            25       New York         Frontend
1             102      Bob            30  San Francisco         Designer
2             103  Charlie            35    Los Angeles            owner
3             104    David            28        Chicago   Developer-back
4             105      Eve            22          Miami           Intern
5             106    Frank            40        Seattle         Frontend
6             107    Grace            29         Boston   Developer-back
7             108   Hannah            31         Denver         Designer
8             109      Ian            27         Austin           Intern
9             110     Jack            33        Houston  Developer-movil
10            111    Kathy            26   Philadelphia  Developer-movil
11            112     Liam            24        Phoenix            sales
12            113     Mona            32      San Diego   Developer-lead
13            114     Nate            42         Dallas           Intern
14            115   Olivia            30        Chicago          Manager
15            116     Paul            28        Detroit        fullstack
16            117    Quinn            27       Columbus            sales
17            118   Rachel            31        Chicago           Intern
18            119      Sam            25   Indianapolis        marketing
19            120     Tina            26          Miami          Manager
20            121    Sonia            39          Miami   Developer-back

    monthly_salary  Annual_Salary
0            70000         840000
1            80000         960000
2           120000        1440000
3            95000        1140000
4            40000         480000
5            72000         864000
6            88000        1056000
7            60000         720000
8            45000         540000
9            98000        1176000
10           91000        1092000
11           65000         780000
12          115000        1380000
13           42000         504000
14          130000        1560000
15          105000        1260000
16           68000         816000
17           43000         516000
18           75000         900000
19          125000        1500000
20           90000        1080000

In [ ]:
# Agregar una nueva columna a 'data_additional' llamada 'Leader_Code' basada en el mapeo de 'Department'
# Nota: pero 103 es el jefe de 113 (porque 113 no puede ser su propio jefe)
department_leader_map = {
    'IT': 113,
    'Design': 115,
    'Management': 120,
    'Internship': 120,
    'Sales': 120,
    'Marketing': 120
}

# Asignar líder por departamento
df_additional['Leader_Code'] = df_additional['Department'].map(department_leader_map)

# Esa regla adicional no es por departamento, sino por empleado concreto, así que es más claro aplicarla luego como corrección puntual.
# Regla especial: 103 es el jefe de 113
df_additional.loc[df_additional['Employee_Code'] == 113, 'Leader_Code'] = 103

print("DataFrame adicional con nueva columna 'Leader_Code':")
print(df_additional)

DataFrame adicional con nueva columna 'Leader_Code':
    Employee_Code  Department  Leader_Code
0             101          IT          113
1             102      Design          115
2             103  Management          120
3             104          IT          113
4             105  Internship          120
5             106          IT          113
6             107          IT          113
7             108      Design          115
8             109  Internship          120
9             110          IT          113
10            111          IT          113
11            112       Sales          120
12            113          IT          103
13            114  Internship          120
14            115  Management          120
15            116          IT          113
16            117       Sales          120
17            118  Internship          120
18            119   Marketing          120
19            120  Management          120
20            121          IT          113

In [ ]:
# Ejemplo de uso de .apply() con una función lambda

df_copy = df.copy()  # buena práctica
# nuevo DataFrame con los campos nombre y salario mensual
df_salary = df_copy[['Employee', 'monthly_salary']]
# Nueva columna 'Salary_in_USD' con conversión a dólares (1 USD = 0.85 EUR)

# Opción 1: usando una operación directa
# df_salary['Salary_in_USD'] = df_salary['monthly_salary'] / 0.85
# print("DataFrame con conversión de salario a USD:")
# print(df_salary)

# Opción 2: usando una función lambda .apply() (con 2 decimales)
# df_salary['Salary_in_USD'] = df_salary['monthly_salary'].apply(lambda x: x / 0.85)
df_salary['Salary_in_USD'] = df_salary['monthly_salary'].apply(lambda x: round(x / 0.85, 2))
print("DataFrame con conversión de salario a USD (usando .apply()):")
print(df_salary)

DataFrame con conversión de salario a USD (usando .apply()):
   Employee  monthly_salary  Salary_in_USD
0     Alice           70000       82352.94
1       Bob           80000       94117.65
2   Charlie          120000      141176.47
3     David           95000      111764.71
4       Eve           40000       47058.82
5     Frank           72000       84705.88
6     Grace           88000      103529.41
7    Hannah           60000       70588.24
8       Ian           45000       52941.18
9      Jack           98000      115294.12
10    Kathy           91000      107058.82
11     Liam           65000       76470.59
12     Mona          115000      135294.12
13     Nate           42000       49411.76
14   Olivia          130000      152941.18
15     Paul          105000      123529.41
16    Quinn           68000       80000.00
17   Rachel           43000       50588.24
18      Sam           75000       88235.29
19     Tina          125000      147058.82
20    Sonia           90000      105882.35

/tmp/ipykernel_2743/3381603782.py:13: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_salary['Salary_in_USD'] = df_salary['monthly_salary'].apply(lambda x: round(x / 0.85, 2))

In [183]:
print("----- Uniendo DataFrames -----")
copia_df = df.copy()
# eliminar columnas no necesarias para el merge
copia_df = copia_df.drop(columns=['City','Employee_Age', 'monthly_salary', 'Annual_Salary'])

df_merged = pd.merge(
    copia_df, df_additional,
    left_on='Employee_Code',
    right_on='Employee_Code',
    how='inner'
    )
print("DataFrame unido (merge) por 'Employee_Code':")
print(df_merged)

----- Uniendo DataFrames -----
DataFrame unido (merge) por 'Employee_Code':
    Employee_Code Employee       Occupation  Department  Leader_Code
0             101    Alice         Frontend          IT          113
1             102      Bob         Designer      Design          115
2             103  Charlie            owner  Management          120
3             104    David   Developer-back          IT          113
4             105      Eve           Intern  Internship          120
5             106    Frank         Frontend          IT          113
6             107    Grace   Developer-back          IT          113
7             108   Hannah         Designer      Design          115
8             109      Ian           Intern  Internship          120
9             110     Jack  Developer-movil          IT          113
10            111    Kathy  Developer-movil          IT          113
11            112     Liam            sales       Sales          120
12            113     Mona   Developer-lead          IT          113
13            114     Nate           Intern  Internship          120
14            115   Olivia          Manager  Management          120
15            116     Paul        fullstack          IT          113
16            117    Quinn            sales       Sales          120
17            118   Rachel           Intern  Internship          120
18            119      Sam        marketing   Marketing          120
19            120     Tina          Manager  Management          120
20            121    Sonia   Developer-back          IT          113

In [192]:
# pequeño dataframe con valores nulos
data_with_nans = {
    'Employee': ['Alice', 'Bob', 'Charlie', 'David', 'Eve'],
    'Age': [25, None, 35, None, 22],
    'City': ['New York', 'San Francisco', None, 'Chicago', 'Miami'],
    'monthly_salary': [70000, 80000, None, 95000, 40000]
}
df_with_nans = pd.DataFrame(data_with_nans)
print("DataFrame con valores nulos:")
print(df_with_nans)

DataFrame con valores nulos:
  Employee   Age           City  monthly_salary
0    Alice  25.0       New York         70000.0
1      Bob   NaN  San Francisco         80000.0
2  Charlie  35.0           None             NaN
3    David   NaN        Chicago         95000.0
4      Eve  22.0          Miami         40000.0

In [193]:
# Detectar valores nulos en el DataFrame
nulos = df_with_nans.isnull()
print("Valores nulos en el DataFrame:")
print(nulos)

Valores nulos en el DataFrame:
   Employee    Age   City  monthly_salary
0     False  False  False           False
1     False   True  False           False
2     False  False   True            True
3     False   True  False           False
4     False  False  False           False

In [200]:
# Contar valores nulos por columna en el DataFrame
nulos_por_columna = df_with_nans.isnull().sum()
print("Cantidad de valores nulos por columna:")
print(nulos_por_columna)
print("-----"*7)
# Contar valores nulos en una columna específica
print("Cantidad de valores nulos en la columna 'Age':")
print(df_with_nans['Age'].isna().sum())

Cantidad de valores nulos por columna:
Employee          0
Age               2
City              1
monthly_salary    1
dtype: int64
-----------------------------------
Cantidad de valores nulos en la columna 'Age':
2

In [ ]:
# Contar valores no nulos por columna en el DataFrame
no_nulos_por_columna = df_with_nans.notnull().sum()
print("Cantidad de valores no nulos por columna:")
print(no_nulos_por_columna)

Cantidad de valores no nulos por columna:
Employee          5
Age               3
City              4
monthly_salary    4
dtype: int64