La idea es recopopilar todas las acciones de limpieza, estructuración y reducción del dataset que se han realizado en los notebooks previos, para tener un resumen claro de lo que se ha hecho hasta ahora.

In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import io
# CONFIGURACION GENERAL_ Solo para visualización; Esto afecta a todos los print de numpy que hagas después
np.set_printoptions(precision=3, suppress=True)#precision=3→3decimales;suppress=True→no usar notación científica
# un dato de fecha se ve asi: 2024-06-01T12:00:00Z

# 1. Tu variable con los datos  con valores null, NaN, None, etc.
data_string = """ID,Factura,Fecha,Producto,Categoría,Ventas,Precio Unitario,Total Ventas,Región
1,FN-1001,2026-01-02 10:15:00,Laptop,Electrónica,15,1200.00,18000.00$,Norte
2,FS-2001,2026-01-04 15:40:00,Monitor,Computación,8,500.00,4OOO.00,Sur
3,FN-1002,2026-01-05 09:20:00,Teclado,Accesorios,25,50.00,12S0.00$,Norte
4,FE-3001,2026-01-08 14:10:00,Laptop,Electrónica,10,1100.00,11000.00,Este
5,FO-4001,2026-01-10 11:30:00,Tablet,Computación,20,700.00,14000.00,Oeste
6,FN-1003,2026-01-12 16:45:00,Impresora,Oficina,5,400.00,2000.00$,Norte
7,FO-4002,2026-01-13 08:55:00,Escáner,Oficina,5,210.00,1050.00,Oeste
8,FE-3002,2026-01-14 13:20:00,Mouse,Accesorios,40,20.00,800.00,Este
9,FO-4003,2026-01-15 17:05:00,Monitor,Computación,12,450.00,5400.00,Oeste
10,FN-1004,2026-01-16 09:15:00,Tablet,Computación,18,750.00,13500.00$,Norte
11,FS-2002,2026-01-18 14:30:00,Teclado,Accesorios,22,55.00,1210.00,Sur
12,FE-3003,2026-01-19 11:20:00,Impresora,Oficina,7,420.00,2940.00,Este
13,FO-4004,2026-01-20 15:45:00,Auriculares,Accesorios,10,80.00,800.00,Oeste
14,FN-1005,2026-01-22 10:05:00,Mouse,Accesorios,35,25.00,875.00$,Norte
15,FS-2003,2026-01-24 16:30:00,Laptop,Electrónica,18,1150.00,20700.00,Sur
16,FE-3004,2026-01-25 09:50:00,Tablet,Computación,15,680.00,10200.00,Este
17,FO-4005,2026-01-27 13:15:00,Monitor,Computación,10,480.00,4800.00,Oeste
18,FN-1006,2026-01-28 14:40:00,Teclado,Accesorios,30,60.00,1800.00$,Norte
19,FS-2004,2026-01-29 11:25:00,Impresora,Oficina,12,450.00,5400.00,Sur
21,FN-1007,2026-01-30 08:30:00,Webcam,Accesorios,15,85.00,None$,Norte
22,FN-1008,2026-01-31 17:50:00,Micrófono,Audio,8,None,3200.00$,Norte
23,FO-4006,2026-02-01 10:00:00,Escáner,,5,210.00,1050.00,Oeste
24,FS-2005,2026-02-02 14:30:00,Silla Gamer,Oficina,12,350.00,,Sur
25,FE-3005,2026-02-04 09:15:00,Disco Duro,Computación,NaN,120.00,240.00,Este
26,FN-1009,2026-02-05 11:20:00,Cargador,Accesorios,20,25.00,500.00,null
27,FN-1010,2026-02-07 16:40:00,Monitor,Computación,null,450.00,sin dato,Norte
28,FS-2006,2026-02-08 13:00:00,Teclado,Accesorios,25,55.00,1375.00,null
29,FS-2007,2026-02-10 10:10:00,Micrófono,Audio,10,null,4000.00,Sur
30,FO-4007,2026-02-11 15:20:00, Cable USB,Accesorios   ,10,80.00,800.00,Oeste
30,FE-3006,2026-02-12 09:45:00, Cable USB,Accesorios,null,null,800.00,Este
31,FN-1011,2026-02-13 12:00:00, ssd externo,Computación,null,150.00,0$,Norte
32,FS-2008,2026-02-14 14:15:00,   ,Computación,null,150.00,0,Sur
33,FO-4007,2026-02-11 15:20:00, Cable USB,Accesorios ,10,80.00,800.00,Oeste
"""
     
'''
NOTA
None (Fila 21): Es el nulo nativo de Python. Pandas suele convertirlo automáticamente a NaN en columnas numéricas.
Espacio vacío ,, (Fila 22 y 23): Es lo más común en archivos CSV. Pandas lo detectará inmediatamente como un valor faltante.
NaN (Fila 25): Significa Not a Number. Es el estándar de NumPy y Pandas para representar datos nulos en columnas de números.
null (Fila 26): Es común si los datos vienen de una base de datos SQL o de un archivo JSON.
'''

df = pd.read_csv(io.StringIO(data_string))

# data = {
#     "ID": [1,2,3,4,5,6,7,8,9,10],
#     "Producto": ["Laptop", "Monitor", "Teclado", "Laptop", "Tablet", "Impresora", "Smartphone", "Mouse", "Monitor", "Tablet"],
#     "Categoría": ["Electrónica", "Computación", "Accesorios", "Electrónica", "Computación", "Oficina", "Electrónica", "Accesorios", "Computación", "Computación"],
#     "Ventas": [15, 8, 25, 10, 20, 5, 30, 40, 12, 18],
#     "Precio Unitario": [1200, 500, 50, 1100, 700, 400, 800, 20, 450, 750],
#     "Total Ventas": [18000, 4000, 1250, 11000, 14000, 2000, 24000, 800, 5400, 13500],
#     "Región": ["Norte", "Sur", "Norte", "Este", "Oeste", "Norte", "Sur", "Este", "Oeste", "Norte"]
# }

In [ ]:
print(df.dtypes)

ID                   int64
Factura                str
Fecha                  str
Producto               str
Categoría              str
Ventas             float64
Precio Unitario    float64
Total Ventas           str
Región                 str
dtype: object

**Normalización BASICA de texto**

In [ ]:
# Total Ventas está como object (texto) y queremos convertirlo a numérico (float) para poder hacer cálculos con él, por tanto:

# copia- nulos antes de intentar la conversión
nulos_originales = df["Total Ventas"].isna() # PARA VALIDACION

# Quitamos el signo $ y las comas (si las hubiera para miles)
# Usamos .replace con regex=True para que busque los símbolos en cualquier parte del texto
df["Total Ventas"] = (
    df["Total Ventas"]
    # .str.replace(r"[\$,€£]", "", regex=True) # Quita $ y ,
    .str.replace(r"[\$,€£]", "", regex=True) # Quita $ y , (y otros símbolos si los hubiera)
        # regex es necesario para que busque el símbolo en cualquier parte del texto, no solo al principio o al final.
        # valor 'True' es necesario para que reemplace todas las ocurrencias, no solo la primera.
        # valor 'False' haría que solo reemplace la primera ocurrencia.
    .str.replace(r"[oOsS]", "0", regex=True)   # CAMBIA 'o' u 'O' por '0'
    .str.strip()                          # Quita espacios laterales
)

# Convertimos a número (float) RED DE SEGURIDAD - Pero validar casos como 'o' en lugar de '0'
df["Total Ventas"] = pd.to_numeric(df["Total Ventas"], errors='coerce')
# errors='coerce' es vital: si encuentra algo que no puede convertir (ej. "null"), 
# en lugar de dar error, lo transforma en NaN.

# Identificamos los "Nuevos Nulos" (los que fallaron por caracteres extraños)
fallas_conversion = df[df["Total Ventas"].isna() & ~nulos_originales]
columnas_interes = ["ID", "Producto", "Ventas", "Precio Unitario", "Total Ventas"]

if not fallas_conversion.empty:
    print("❌ REGISTROS QUE NO SE PUDIERON CONVERTIR:")
    print(fallas_conversion[columnas_interes])
    print(df["Total Ventas"].dtype)
else:
    print("✅ ¡Éxito! Todos los registros se convirtieron correctamente.")
    # 3. Verificamos el resultado
    print(df["Total Ventas"].dtype)

❌ REGISTROS QUE NO SE PUDIERON CONVERTIR:
    ID Producto  Ventas  Precio Unitario  Total Ventas
19  21   Webcam    15.0             85.0           NaN
25  27  Monitor     NaN            450.0           NaN
float64

**Normalización BASICA de texto**

In [ ]:

# 1. Definimos las columnas que queremos limpiar
cols_a_limpiar = ["Producto", "Categoría", "Región"]

for col in cols_a_limpiar:
    # A. Quitamos espacios al inicio y al final
    df[col] = df[col].str.strip() # eliminar espacios al inicio y al final de cada valor en la columna
    # df[col].replace("", np.nan, inplace=True) # No usamos esta línea porque ya la lógica de detección de celdas basura lo hará en el siguiente paso.

    # B. Identificamos celdas que NO tienen contenido real (letras o números)
    # Usamos tu lógica del operador de negación (~) y el accesor .str
    # Esto atrapará celdas con solo espacios, puntos, o vacías
    mascara_basura = ~df[col].str.contains(r"[a-zA-Z0-9]", na=False)
        # ~ → operador de negación para seleccionar filas que NO cumplen la condición
        # na=False → para evitar que los NaN se consideren como True (ya que no contienen letras ni números)
        # df["Producto"].str, le esta diciendo a Pandas: "Trata cada celda de esta columna como si fuera un string".

    # C. Asignamos NaN a esas celdas detectadas con problemas
    df.loc[mascara_basura, col] = np.nan

# 2. Opcional: Convertir todo a minúsculas para normalizar 
for col in cols_a_limpiar:
    df[col] = df[col].str.lower()

print("¡Limpieza completada!")


#Nota: En Python puro, las cadenas de texto (str) tienen sus propios métodos, pero contains no es uno de ellos (en Python estándar usarías el operador in). Sin embargo, en Pandas existe el Accesor .str, que es como un portal que te permite aplicar métodos de strings (y algunos extras de Regex) a toda una columna de una sola vez.

¡Limpieza completada!

PENDIENTE:

PENDIENTE CONVERSIÓN DE FECHA a formato datetime (si es necesario) para análisis temporal. PERO PRIMERO VAMOS A VALIDAR NULL?

VALIDAR SI ALGUN DATO OBJETO-STRING SE PUEDE CONVERTIR A DATO CATEGÓRICO (si tiene pocas categorías únicas) PARA OPTIMIZAR MEMORIA Y ANÁLISIS.






QUE PASA SI CONVIERTO 'Total Ventas' a NUMERICO Y HAY VALORES NO NUMÉRICOS? (Ejemplo: "N/A", "Desconocido", NULL etc.)
     Esto generará NaN en esas filas?
     Sera importante revisar y limpiar esos valores antes de la conversión.

In [ ]:
print("###########"*10)
print("\n-------- CABECERA  ------- \n")
print(df.head(3))
print("-----"*20)

##############################################################################################################

-------- CABECERA  -------

   ID  Factura                Fecha Producto    Categoría  Ventas  \
0   1  FN-1001  2026-01-02 10:15:00   laptop  electrónica    15.0
1   2  FS-2001  2026-01-04 15:40:00  monitor  computación     8.0
2   3  FN-1002  2026-01-05 09:20:00  teclado   accesorios    25.0

   Precio Unitario  Total Ventas Región
0           1200.0       18000.0  norte
1            500.0        4000.0    sur
2             50.0        1200.0  norte
----------------------------------------------------------------------------------------------------

In [ ]:
print("###########"*10)
print("\n-------- FOOTER (ultimos 6 registros)  ------- \n")
print(df.tail(7))
print("____"*20)

# Pandas maneja los None como NaN (Not a Number) automáticamente
# En columnas numéricas o de texto, None se convierte en NaN
# Pandas manejo los espacios vacíos (,,) como NaN automáticamente
# Pandas maneja los null como NaN automáticamente.
# Pandas maneja los NaN como valores faltantes en columnas numéricas

##############################################################################################################

-------- FOOTER (ultimos 6 registros)  -------

    ID  Factura                Fecha     Producto    Categoría  Ventas  \
26  28  FS-2006  2026-02-08 13:00:00      teclado   accesorios    25.0
27  29  FS-2007  2026-02-10 10:10:00    micrófono        audio    10.0
28  30  FO-4007  2026-02-11 15:20:00    cable usb   accesorios    10.0
29  30  FE-3006  2026-02-12 09:45:00    cable usb   accesorios     NaN
30  31  FN-1011  2026-02-13 12:00:00  ssd externo  computación     NaN
31  32  FS-2008  2026-02-14 14:15:00          NaN  computación     NaN
32  33  FO-4007  2026-02-11 15:20:00    cable usb   accesorios    10.0

    Precio Unitario  Total Ventas Región
26             55.0        1375.0    NaN
27              NaN        4000.0    sur
28             80.0         800.0  oeste
29              NaN         800.0   este
30            150.0           0.0  norte
31            150.0           0.0    sur
32             80.0         800.0  oeste
________________________________________________________________________________

In [ ]:
#Dimensión del dataset
# fila, colum = df.shape
filas = df.shape[0]  # Número de filas
columnas = df.shape[1]  # Número de columnas
print("###########"*10)
print("\n-------- Dimensión del dataset -------  \n")
print(f"El dataset tiene {filas} filas y {columnas} columnas.")
print("-----"*20)

##############################################################################################################

-------- Dimensión del dataset -------

El dataset tiene 33 filas y 9 columnas.
----------------------------------------------------------------------------------------------------

In [ ]:
# Columnas del dataset
print("###########"*10)
print("\n--------  Columnas del dataset -------  \n")
columnas = df.columns
print("Las columnas del dataset son:")
print(columnas)

print("-----"*20)

##############################################################################################################

--------  Columnas del dataset -------

Las columnas del dataset son:
Index(['ID', 'Factura', 'Fecha', 'Producto', 'Categoría', 'Ventas',
       'Precio Unitario', 'Total Ventas', 'Región'],
      dtype='str')
----------------------------------------------------------------------------------------------------

In [ ]:
# Tipos de datos de cada columna
print("###########"*10)
print("------ Tipos de datos de cada columna: ------- \n")
print(df.dtypes)
print("-----"*20)

##############################################################################################################
------ Tipos de datos de cada columna: -------

ID                   int64
Factura                str
Fecha                  str
Producto               str
Categoría              str
Ventas             float64
Precio Unitario    float64
Total Ventas       float64
Región                 str
dtype: object
----------------------------------------------------------------------------------------------------

In [ ]:
print("###########"*10)
print("------ Información general del dataset: ------- \n")
df.info()
print("-----"*20)

##############################################################################################################
------ Información general del dataset: -------

<class 'pandas.DataFrame'>
RangeIndex: 33 entries, 0 to 32
Data columns (total 9 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   ID               33 non-null     int64
 1   Factura          33 non-null     str
 2   Fecha            33 non-null     str
 3   Producto         32 non-null     str
 4   Categoría        32 non-null     str
 5   Ventas           28 non-null     float64
 6   Precio Unitario  30 non-null     float64
 7   Total Ventas     30 non-null     float64
 8   Región           31 non-null     str
dtypes: float64(3), int64(1), str(5)
memory usage: 2.4 KB
----------------------------------------------------------------------------------------------------

In [ ]:
# Acceder a una columna específica (por ejemplo, 'Total Ventas')   [[[EXTRA]]]
daily_sales = df['Total Ventas']
print("Serie 'Total Ventas':")
print(daily_sales)
print(type(daily_sales))

print("------ Tercer valor de la columna 'Total Ventas': -------")
print(daily_sales[2])

Serie 'Total Ventas':
0     18000.0
1      4000.0
2      1200.0
3     11000.0
4     14000.0
5      2000.0
6      1050.0
7       800.0
8      5400.0
9     13500.0
10     1210.0
11     2940.0
12      800.0
13      875.0
14    20700.0
15    10200.0
16     4800.0
17     1800.0
18     5400.0
19        NaN
20     3200.0
21     1050.0
22        NaN
23      240.0
24      500.0
25        NaN
26     1375.0
27     4000.0
28      800.0
29      800.0
30        0.0
31        0.0
32      800.0
Name: Total Ventas, dtype: float64
<class 'pandas.Series'>
------ Tercer valor de la columna 'Total Ventas': -------
1200.0

In [ ]:
resumen_limpio  = df.describe().T[['count', 'mean', 'min', '50%', 'max']].rename(columns={
    'count': 'Cantidad',
    'mean': 'Promedio',
    'min': 'Mínimo',
    '50%': 'Mediana',
    'max': 'Máximo'
})
print("###########"*10)
print("\n-------- ESTADISTICAS -------\n")
print(resumen_limpio)
print("-----"*20)

##############################################################################################################

-------- ESTADISTICAS -------

                 Cantidad     Promedio  Mínimo  Mediana   Máximo
ID                   33.0    17.303030     1.0     17.0     33.0
Ventas               28.0    15.428571     5.0     12.0     40.0
Precio Unitario      30.0   351.166667    20.0    210.0   1200.0
Total Ventas         30.0  4414.666667     0.0   1587.5  20700.0
----------------------------------------------------------------------------------------------------

In [ ]:
# Contar valores únicos en cada columna.
print("###########"*10)
print("------- Número de valores únicos por columna:---------")
print("Número de valores únicos por columna:")
valores_unicos_antes_de_limpieza = df.nunique().sort_values()
display(valores_unicos_antes_de_limpieza)
print("-----"*20)

##############################################################################################################
------- Número de valores únicos por columna:---------
Número de valores únicos por columna:

Región              4
Categoría           5
Ventas             13
Producto           15
Total Ventas       22
Precio Unitario    22
ID                 32
Fecha              32
Factura            32
dtype: int64

----------------------------------------------------------------------------------------------------

In [ ]:
# Contar valores nulos en cada columna.    [[[NULOS]]]
num_null = df.isnull().sum()
print("###########"*10)
print("--- Número de valores nulos por columna:---")
display(num_null)
print("-----"*20)

# Realmente no son nulos, sino que son valores faltantes representados por None, NaN, null o espacios vacíos. Pandas los interpreta como NaN automáticamente.

##############################################################################################################
--- Número de valores nulos por columna:---

ID                 0
Factura            0
Fecha              0
Producto           1
Categoría          1
Ventas             5
Precio Unitario    3
Total Ventas       3
Región             2
dtype: int64

----------------------------------------------------------------------------------------------------

In [ ]:
# Filas que tienen valores nulos
nulos = df.isnull().sum()
# nulos_na = df.isna().sum() # SINONIMO  de isnull() # 
print("Valores nulos por columna:")
print(nulos[nulos > 0])

Valores nulos por columna:
Producto           1
Categoría          1
Ventas             5
Precio Unitario    3
Total Ventas       3
Región             2
dtype: int64

In [ ]:
# Porcentaje de valores nulos por columna
#df.isna().mean()*100).round(2))
# print(f"{(df.isna().mean()*100).round(2)}")

# reporte_nulos = (df.isnull().sum() / len(df) * 100).round(2)
reporte_nulos = (df.isna().mean() * 100).round(2).map("{:.2f} %".format)


print("Porcentaje de valores nulos por columna:")
print(reporte_nulos)

Porcentaje de valores nulos por columna:
ID                  0.00 %
Factura             0.00 %
Fecha               0.00 %
Producto            3.03 %
Categoría           3.03 %
Ventas             15.15 %
Precio Unitario     9.09 %
Total Ventas        9.09 %
Región              6.06 %
dtype: str

In [ ]:
# Filas que contienen al menos un valor nulo
row_null = df[df.isnull().any(axis=1)]
display(row_null)

,ID,Factura,Fecha,Producto,Categoría,Ventas,Precio Unitario,Total Ventas,Región
19,21,FN-1007,2026-01-30 08:30:00,webcam,accesorios,15.0,85.0,NaN,norte
20,22,FN-1008,2026-01-31 17:50:00,micrófono,audio,8.0,NaN,3200.0,norte
21,23,FO-4006,2026-02-01 10:00:00,escáner,NaN,5.0,210.0,1050.0,oeste
22,24,FS-2005,2026-02-02 14:30:00,silla gamer,oficina,12.0,350.0,NaN,sur
23,25,FE-3005,2026-02-04 09:15:00,disco duro,computación,NaN,120.0,240.0,este
24,26,FN-1009,2026-02-05 11:20:00,cargador,accesorios,20.0,25.0,500.0,NaN
25,27,FN-1010,2026-02-07 16:40:00,monitor,computación,NaN,450.0,NaN,norte
26,28,FS-2006,2026-02-08 13:00:00,teclado,accesorios,25.0,55.0,1375.0,NaN
27,29,FS-2007,2026-02-10 10:10:00,micrófono,audio,10.0,NaN,4000.0,sur
29,30,FE-3006,2026-02-12 09:45:00,cable usb,accesorios,NaN,NaN,800.0,este
30,31,FN-1011,2026-02-13 12:00:00,ssd externo,computación,NaN,150.0,0.0,norte
31,32,FS-2008,2026-02-14 14:15:00,NaN,computación,NaN,150.0,0.0,sur

In [ ]:
# duplicado absoluto (CUIDADO) Cuenta los registros completos que son idénticos en todas sus columnas.
# df.duplicated().sum()

# duplicado parcial. (RECOMENDADO)
# Buscamos duplicados en la columna 'Factura'
facturas_repetidas = df[df.duplicated(subset=['Factura'], keep=False)]
    # tambien se puede sobre Coloumna 'ID' para ID duplicados o cualquier otra que se considere clave única.

print("Registros con el mismo código de factura:")
print(facturas_repetidas.sort_values(by='Factura'))

Registros con el mismo código de factura:
    ID  Factura                Fecha   Producto   Categoría  Ventas  \
28  30  FO-4007  2026-02-11 15:20:00  cable usb  accesorios    10.0
32  33  FO-4007  2026-02-11 15:20:00  cable usb  accesorios    10.0

    Precio Unitario  Total Ventas Región
28             80.0         800.0  oeste
32             80.0         800.0  oeste

**MANEJO DE DUPLICADOS**

In [ ]:
df = df.drop_duplicates(subset=['Factura'], keep='first')         # [[[drop_duplicates()]]]

facturas_repetidas = df[df.duplicated(subset=['Factura'], keep=False)]
if not facturas_repetidas.empty:
    print("Aún hay registros con el mismo código de factura.")
else:
    print("No hay registros con el mismo código de factura.")
    print(facturas_repetidas.sort_values(by='Factura'))

No hay registros con el mismo código de factura.
Empty DataFrame
Columns: [ID, Factura, Fecha, Producto, Categoría, Ventas, Precio Unitario, Total Ventas, Región]
Index: []

In [ ]:
# 1. Obtenemos los valores únicos de cada columna
unique_values = {col: df[col].unique() for col in df.columns}

print("=== AUDITORÍA DE VALORES ÚNICOS ===\n")

for col, values in unique_values.items():
    print(f'📍 Columna: {col.upper()}')
    print(f'   Total únicos: {len(values)}')
    
    # Mostramos los primeros 15 para no saturar la pantalla
    # El uso de repr() ayuda a ver espacios invisibles como '  '
    sample_values = [repr(v) for v in values[:8]] 
    print(f'   Muestra: {", ".join(sample_values)}')
    
    # Alerta especial si hay nulos reales detectados por Pandas
    if df[col].isnull().any():
        print(f'   ⚠️ ATENCIÓN: Esta columna tiene nulos reales (NaN)')
        
    print('-' * 50)

=== AUDITORÍA DE VALORES ÚNICOS ===

📍 Columna: ID
   Total únicos: 31
   Muestra: np.int64(1), np.int64(2), np.int64(3), np.int64(4), np.int64(5), np.int64(6), np.int64(7), np.int64(8)
--------------------------------------------------
📍 Columna: FACTURA
   Total únicos: 32
   Muestra: 'FN-1001', 'FS-2001', 'FN-1002', 'FE-3001', 'FO-4001', 'FN-1003', 'FO-4002', 'FE-3002'
--------------------------------------------------
📍 Columna: FECHA
   Total únicos: 32
   Muestra: '2026-01-02 10:15:00', '2026-01-04 15:40:00', '2026-01-05 09:20:00', '2026-01-08 14:10:00', '2026-01-10 11:30:00', '2026-01-12 16:45:00', '2026-01-13 08:55:00', '2026-01-14 13:20:00'
--------------------------------------------------
📍 Columna: PRODUCTO
   Total únicos: 16
   Muestra: 'laptop', 'monitor', 'teclado', 'tablet', 'impresora', 'escáner', 'mouse', 'auriculares'
   ⚠️ ATENCIÓN: Esta columna tiene nulos reales (NaN)
--------------------------------------------------
📍 Columna: CATEGORÍA
   Total únicos: 6
   Muestra: 'electrónica', 'computación', 'accesorios', 'oficina', 'audio', nan
   ⚠️ ATENCIÓN: Esta columna tiene nulos reales (NaN)
--------------------------------------------------
📍 Columna: VENTAS
   Total únicos: 14
   Muestra: np.float64(15.0), np.float64(8.0), np.float64(25.0), np.float64(10.0), np.float64(20.0), np.float64(5.0), np.float64(40.0), np.float64(12.0)
   ⚠️ ATENCIÓN: Esta columna tiene nulos reales (NaN)
--------------------------------------------------
📍 Columna: PRECIO UNITARIO
   Total únicos: 23
   Muestra: np.float64(1200.0), np.float64(500.0), np.float64(50.0), np.float64(1100.0), np.float64(700.0), np.float64(400.0), np.float64(210.0), np.float64(20.0)
   ⚠️ ATENCIÓN: Esta columna tiene nulos reales (NaN)
--------------------------------------------------
📍 Columna: TOTAL VENTAS
   Total únicos: 23
   Muestra: np.float64(18000.0), np.float64(4000.0), np.float64(1200.0), np.float64(11000.0), np.float64(14000.0), np.float64(2000.0), np.float64(1050.0), np.float64(800.0)
   ⚠️ ATENCIÓN: Esta columna tiene nulos reales (NaN)
--------------------------------------------------
📍 Columna: REGIÓN
   Total únicos: 5
   Muestra: 'norte', 'sur', 'este', 'oeste', nan
   ⚠️ ATENCIÓN: Esta columna tiene nulos reales (NaN)
--------------------------------------------------

In [ ]:
# Filas donde la columna 'Región' tiene valores nulos (Consulta especifica EXTRA)
print(  df[df["Región"].isna()]  )

    ID  Factura                Fecha  Producto   Categoría  Ventas  \
24  26  FN-1009  2026-02-05 11:20:00  cargador  accesorios    20.0
26  28  FS-2006  2026-02-08 13:00:00   teclado  accesorios    25.0

    Precio Unitario  Total Ventas Región
24             25.0         500.0    NaN
26             55.0        1375.0    NaN

In [ ]:
# ---------- 5️⃣ TRATAR REGIÓN ----------
# opción A: marcar como desconocida
# df["Región"].fillna("Sin región", inplace=True)

# opción B (alternativa): eliminar filas sin región                                  (CUIDADO)
df = df.dropna(subset=["Región"])
    # dropna() permite eliminar filas que tengan valores nulos en las columnas especificadas en subset.
    # NOTA .dropna(axis=1) es para eliminar columnas que tengan valores nulos, no filas. (NO CONFUNDIR - NO ELIMINAR COLUMNAS, SOLO FILAS)

In [ ]:
# ----------  VALIDAR ----------
#pandas toma los valores null, NaN, None, etc. como NaN automáticamente, y la limpieza de PRODUCTO se realiza mas adelante
# # Convertimos strings como "null" o "NaN" y espacios vacíos a nulos reales (np.nan)
# df.replace(["null", "NaN", ""], np.nan, inplace=True)
# # Limpiamos espacios en blanco accidentales ("  ")
# df['Producto'] = df['Producto'].str.strip().replace("", np.nan)

**Limpieza de Categoria**

In [ ]:
# ---------- 0️⃣ PREPARACIÓN: IDENTIFICAR Y GUARDAR ÍNDICES ----------

# Buscamos las filas donde 'Categoría' es nula
indices_nulos_cat = df[df["Categoría"].isna()].index
print(f"Se encontraron {len(indices_nulos_cat)} filas con Categoría nula.")
print("\n--- FILAS ANTES DE LA LIMPIEZA (Solo las afectadas) ---")
print(df.loc[indices_nulos_cat])


# ---------- 1️⃣ TU CÓDIGO DE LIMPIEZA ----------

# Aplicamos la lógica de completar por producto o poner 'Desconocido'
df["Categoría"] = df.groupby("Producto")["Categoría"]\
                    .transform(lambda x: x.fillna(x.mode()[0] if not x.mode().empty else "Desconocido"))

# Si aún quedan vacíos (casos donde no hubo coincidencia)
# df["Categoría"].fillna("Desconocido", inplace=True) # Descontinuado 
df["Categoría"] = df["Categoría"].fillna("Desconocido")
# Red de seguridad para cualquier caso que se nos haya pasado:
# ✔ productos únicos sin categoría
# ✔ datos corruptos
# ✔ inconsistencias
# fillna() es un método de Pandas que se utiliza para rellenar los valores faltantes (NaN) en un DataFrame o Serie. En este caso, se está utilizando para asegurarse de que cualquier valor faltante en la columna 'Categoría' se rellene con "Desconocido" después de intentar completar por producto.

"""
df.groupby("Producto") -> Agrupa filas que tienen el mismo producto.
Grupo: Mouse:
Accesorios
NaN
Accesorios
df.groupby("Producto")["Categoría"] -> Ahora cada grupo solo contiene esa columna.
transform(): ->
✔ aplica una función a cada grupo
✔ devuelve el resultado con el mismo tamaño del DataFrame
✔ permite reasignarlo a la columna original
Sin transform(), perderías la forma original (n°filas, etc).
ambda x: ...  ->  x representa la columna Categoría dentro de cada grupo.
x.fillna(...) -> Rellena los valores faltantes dentro del grupo.
x.mode()[0] -> valor usamos para rellenar
mode() -> Devuelve una serie, tomamos el valor más frecuente.
if not x.mode().empty  -> Rellenar
Si está vacío:  ->   else "Desconocido"
"""

# ---------- 2️⃣ VERIFICACIÓN: COMPARAR EL DESPUÉS ----------

print("\n--- FILAS DESPUÉS DE LA LIMPIEZA (Mismos índices) ---")
# Usamos .loc con los índices que guardamos al principio
print(df.loc[indices_nulos_cat])
# df[df["Categoría"] == "Desconocido"]

Se encontraron 1 filas con Categoría nula.

--- FILAS ANTES DE LA LIMPIEZA (Solo las afectadas) ---
    ID  Factura                Fecha Producto Categoría  Ventas  \
21  23  FO-4006  2026-02-01 10:00:00  escáner       NaN     5.0

    Precio Unitario  Total Ventas Región
21            210.0        1050.0  oeste

--- FILAS DESPUÉS DE LA LIMPIEZA (Mismos índices) ---
    ID  Factura                Fecha Producto Categoría  Ventas  \
21  23  FO-4006  2026-02-01 10:00:00  escáner   oficina     5.0

    Precio Unitario  Total Ventas Región
21            210.0        1050.0  oeste

In [ ]:
# Vista mas legible del código para completar la categoría faltante con la moda por producto, y si no hay moda, asignar "Desconocido".

# def completar_categoria(grupo):
#     moda = grupo.mode()

#     if not moda.empty:
#         return grupo.fillna(moda[0])
#     else:
#         return grupo.fillna("Desconocido")

# df["Categoría"] = df.groupby("Producto")["Categoría"].transform(completar_categoria)
# df["Categoría"] = df["Categoría"].fillna("Desconocido")

**LIMPIAR PRECIO UNITARIO**

In [ ]:
# ---------- 0️⃣ PREPARACIÓN: IDENTIFICAR Y GUARDAR ÍNDICES ----------

# Buscamos las filas donde 'Precio Unitario' es nula
indices_nulos_cat = df[df["Precio Unitario"].isna()].index
print(f"Se encontraron {len(indices_nulos_cat)} filas con Precio Unitario nula.")
print("\n--- FILAS ANTES DE LA LIMPIEZA (Solo las afectadas) ---")
print(df.loc[indices_nulos_cat])


# ---------- 1️⃣ LIMPIAR PRECIO UNITARIO ----------


# 1️⃣ Calcular precio unitario si faltante pero existen Total_Ventas y Ventas
# Precio Unitario = Total Ventas / Ventas
mask = df["Precio Unitario"].isna() & df["Total Ventas"].notna() & df["Ventas"].notna()
# mask es un filtro lógico que identifica filas donde:
# -falta el precio unitario
# -sí existe el total de ventas
# -sí existe la cantidad vendida
# print("Validando la lógica 'mask':")
# print(mask)
# 18    False
# 19    False
# 20     True
# 21    False
print("\n--- FILAS CON PRECIO UNITARIO NULO PERO TOTAL VENTAS Y VENTAS NO NULOS ---")
print(df.loc[mask])
# --- FILAS CON PRECIO UNITARIO NULO PERO TOTAL VENTAS Y VENTAS NO NULOS ---
#     ID   Producto Categoría  Ventas  Precio Unitario  Total Ventas Región
# 20  22  Micrófono     Audio     8.0              NaN        3200.0  Norte
# 27  29  Impresora   Oficina    10.0              NaN        4000.0    Sur
# ignora:
# --  30  Cable USB  Accesorios     NaN              NaN         800.0  Oeste
df.loc[mask, "Precio Unitario"] = df.loc[mask, "Total Ventas"] / df.loc[mask, "Ventas"]

# 2️⃣ Usar promedio del mismo producto
df["Precio Unitario"] = df.groupby("Producto")["Precio Unitario"] \
    .transform(lambda x: x.fillna(x.mean())) # Uso de la Media para rellenar el precio unitario faltante dentro de cada grupo de producto.

# 3️⃣ NO rellenar con promedio global
# df["Precio Unitario"].fillna(df["Precio Unitario"].mean(), inplace=True) 
#       ////  fillna() es capaz de sacar promedio con NULL? R: Sí, fillna() con un valor específico (como la media) puede manejar NaN sin problemas.
# df["Precio Unitario"] = df["Precio Unitario"].fillna(df["Precio Unitario"].mean())
# dejamos NaN si no se pudo inferir


# ---------- 2️⃣ VERIFICACIÓN: COMPARAR EL DESPUÉS ----------
print("\n--- FILAS DESPUÉS DE LA LIMPIEZA (Mismos índices) ---")
# Usamos .loc con los índices que guardamos al principio
print(df.loc[indices_nulos_cat])

Se encontraron 3 filas con Precio Unitario nula.

--- FILAS ANTES DE LA LIMPIEZA (Solo las afectadas) ---
    ID  Factura                Fecha   Producto   Categoría  Ventas  \
20  22  FN-1008  2026-01-31 17:50:00  micrófono       audio     8.0
27  29  FS-2007  2026-02-10 10:10:00  micrófono       audio    10.0
29  30  FE-3006  2026-02-12 09:45:00  cable usb  accesorios     NaN

    Precio Unitario  Total Ventas Región
20              NaN        3200.0  norte
27              NaN        4000.0    sur
29              NaN         800.0   este

--- FILAS CON PRECIO UNITARIO NULO PERO TOTAL VENTAS Y VENTAS NO NULOS ---
    ID  Factura                Fecha   Producto Categoría  Ventas  \
20  22  FN-1008  2026-01-31 17:50:00  micrófono     audio     8.0
27  29  FS-2007  2026-02-10 10:10:00  micrófono     audio    10.0

    Precio Unitario  Total Ventas Región
20              NaN        3200.0  norte
27              NaN        4000.0    sur

--- FILAS DESPUÉS DE LA LIMPIEZA (Mismos índices) ---
    ID  Factura                Fecha   Producto   Categoría  Ventas  \
20  22  FN-1008  2026-01-31 17:50:00  micrófono       audio     8.0
27  29  FS-2007  2026-02-10 10:10:00  micrófono       audio    10.0
29  30  FE-3006  2026-02-12 09:45:00  cable usb  accesorios     NaN

    Precio Unitario  Total Ventas Región
20            400.0        3200.0  norte
27            400.0        4000.0    sur
29             80.0         800.0   este

In [ ]:
row_null = df[df.isnull().any(axis=1)]
display(row_null)

,ID,Factura,Fecha,Producto,Categoría,Ventas,Precio Unitario,Total Ventas,Región
19,21,FN-1007,2026-01-30 08:30:00,webcam,accesorios,15.0,85.0,NaN,norte
22,24,FS-2005,2026-02-02 14:30:00,silla gamer,oficina,12.0,350.0,NaN,sur
23,25,FE-3005,2026-02-04 09:15:00,disco duro,computación,NaN,120.0,240.0,este
25,27,FN-1010,2026-02-07 16:40:00,monitor,computación,NaN,450.0,NaN,norte
29,30,FE-3006,2026-02-12 09:45:00,cable usb,accesorios,NaN,80.0,800.0,este
30,31,FN-1011,2026-02-13 12:00:00,ssd externo,computación,NaN,150.0,0.0,norte
31,32,FS-2008,2026-02-14 14:15:00,NaN,Desconocido,NaN,NaN,0.0,sur

**Limpieza de Ventas**

In [ ]:
# ---------- 0️⃣ PREPARACIÓN: IDENTIFICAR Y GUARDAR ÍNDICES ----------

# Buscamos las filas donde 'Ventas' es nula
indices_nulos_cat = df[df["Ventas"].isna()].index

print(f"Se encontraron {len(indices_nulos_cat)} filas con Ventas nula.")
print("\n--- FILAS ANTES DE LA LIMPIEZA (Solo las afectadas) ---")
print(df.loc[indices_nulos_cat])

# ---------- 1️⃣ LIMPIAR VENTAS ----------

# Primero arreglamos los casos donde Total Ventas es 0
df.loc[df['Total Ventas'] == 0, 'Ventas'] = df['Ventas'].fillna(0)
#filtro de seguridad para paso posterior
# Ubica las filas donde el dinero recaudado es cero, y valida la columna de cantidad vendida,..
# Si en esa fila hay un NaN,  indicar un '0'

# # Luego calculamos: Ventas = Total / Precio (Solo donde Ventas sea NaN, no cero)
df['Ventas'] = df['Ventas'].fillna(df['Total Ventas'] / df['Precio Unitario'])

# # --- 2️⃣ REGLA DE GRUPO: Promedio por producto ---
# df["Ventas"] = df.groupby("Producto")["Ventas"]\
#                  .transform(lambda x: x.fillna(x.mean()))
# # --- 3️⃣ REGLA DE CIERRE: Último recurso ---
# df["Ventas"] = df["Ventas"].fillna(0)
'''
Antes se había propuesto rellenar con el promedio por producto para mantener la coherencia dentro de cada categoría de producto. Pero decidimos no hacerlo porque:
- Podría introducir sesgos si el producto tiene pocos registros o mucha variabilidad.
Se permite dejar el NaN en este caso, ya que no se puede inferir un valor razonable sin más información. Es mejor tener un NaN que un valor incorrecto.
'''

###### NO USADO 
# # rellenar con promedio del producto
# df["Ventas"] = df.groupby("Producto")["Ventas"]\
#                  .transform(lambda x: x.fillna(x.mean()))
# # si aún queda NaN
# # df["Ventas"].fillna(0, inplace=True)
# df ["Ventas"] = df["Ventas"].fillna(0)  


# ---------- 2️⃣ VERIFICACIÓN: COMPARAR EL DESPUÉS ----------

print("\n--- FILAS DESPUÉS DE LA LIMPIEZA (Mismos índices) ---")
# Usamos .loc con los índices que guardamos al principio
print(df.loc[indices_nulos_cat])

Se encontraron 5 filas con Ventas nula.

--- FILAS ANTES DE LA LIMPIEZA (Solo las afectadas) ---
    ID  Factura                Fecha     Producto    Categoría  Ventas  \
23  25  FE-3005  2026-02-04 09:15:00   disco duro  computación     NaN
25  27  FN-1010  2026-02-07 16:40:00      monitor  computación     NaN
29  30  FE-3006  2026-02-12 09:45:00    cable usb   accesorios     NaN
30  31  FN-1011  2026-02-13 12:00:00  ssd externo  computación     NaN
31  32  FS-2008  2026-02-14 14:15:00          NaN  Desconocido     NaN

    Precio Unitario  Total Ventas Región
23            120.0         240.0   este
25            450.0           NaN  norte
29             80.0         800.0   este
30            150.0           0.0  norte
31              NaN           0.0    sur

--- FILAS DESPUÉS DE LA LIMPIEZA (Mismos índices) ---
    ID  Factura                Fecha     Producto    Categoría  Ventas  \
23  25  FE-3005  2026-02-04 09:15:00   disco duro  computación     2.0
25  27  FN-1010  2026-02-07 16:40:00      monitor  computación     NaN
29  30  FE-3006  2026-02-12 09:45:00    cable usb   accesorios    10.0
30  31  FN-1011  2026-02-13 12:00:00  ssd externo  computación     0.0
31  32  FS-2008  2026-02-14 14:15:00          NaN  Desconocido     0.0

    Precio Unitario  Total Ventas Región
23            120.0         240.0   este
25            450.0           NaN  norte
29             80.0         800.0   este
30            150.0           0.0  norte
31              NaN           0.0    sur

**Limpieza de Precio Total Ventas**

In [ ]:
# ---------- 0️⃣ PREPARACIÓN: IDENTIFICAR Y GUARDAR ÍNDICES ----------

# Buscamos las filas donde 'Total Ventas' es nula
indices_nulos_cat = df[df["Total Ventas"].isna()].index

print(f"Se encontraron {len(indices_nulos_cat)} filas con Total Ventas nula.")
print("\n--- FILAS ANTES DE LA LIMPIEZA (Solo las afectadas) ---")
print(df.loc[indices_nulos_cat])

# ---------- 1️⃣ LIMPIAR VENTAS ----------

df["Total Ventas"] = df["Total Ventas"].fillna(
        df["Ventas"] * df["Precio Unitario"]
    )

# tipo de dato de Total Ventas
print("\nTipo de dato de 'Total Ventas' después de la limpieza:")
print(df["Total Ventas"].dtype)

# ---------- 2️⃣ VERIFICACIÓN: COMPARAR EL DESPUÉS ----------

print("\n--- FILAS DESPUÉS DE LA LIMPIEZA (Mismos índices) ---")
# Usamos .loc con los índices que guardamos al principio
print(df.loc[indices_nulos_cat])

Se encontraron 3 filas con Total Ventas nula.

--- FILAS ANTES DE LA LIMPIEZA (Solo las afectadas) ---
    ID  Factura                Fecha     Producto    Categoría  Ventas  \
19  21  FN-1007  2026-01-30 08:30:00       webcam   accesorios    15.0
22  24  FS-2005  2026-02-02 14:30:00  silla gamer      oficina    12.0
25  27  FN-1010  2026-02-07 16:40:00      monitor  computación     NaN

    Precio Unitario  Total Ventas Región
19             85.0           NaN  norte
22            350.0           NaN    sur
25            450.0           NaN  norte

Tipo de dato de 'Total Ventas' después de la limpieza:
float64

--- FILAS DESPUÉS DE LA LIMPIEZA (Mismos índices) ---
    ID  Factura                Fecha     Producto    Categoría  Ventas  \
19  21  FN-1007  2026-01-30 08:30:00       webcam   accesorios    15.0
22  24  FS-2005  2026-02-02 14:30:00  silla gamer      oficina    12.0
25  27  FN-1010  2026-02-07 16:40:00      monitor  computación     NaN

    Precio Unitario  Total Ventas Región
19             85.0        1275.0  norte
22            350.0        4200.0    sur
25            450.0           NaN  norte

**Limpieza de valores nulos en la columna "Producto"**

In [ ]:
# ---------- 0️⃣ PREPARACIÓN: IDENTIFICAR Y GUARDAR ÍNDICES ----------

# Buscamos las filas donde 'Producto' es nula
indices_nulos_cat = df[df["Producto"].isna()].index
print(f"Se encontraron {len(indices_nulos_cat)} filas con Producto nula.")
print("\n--- FILAS ANTES DE LA LIMPIEZA (Solo las afectadas) ---")
print(df.loc[indices_nulos_cat])

# ---------- 1️⃣ TU CÓDIGO DE LIMPIEZA ----------

# df["Producto"].fillna("Desconocido", inplace=True) # Descontinuado 
df["Producto"] = df["Producto"].fillna("Desconocido")

# ---------- 2️⃣ VERIFICACIÓN: COMPARAR EL DESPUÉS ----------
print("\n--- FILAS DESPUÉS DE LA LIMPIEZA (Mismos índices) ---")
# Usamos .loc con los índices que guardamos al principio
print(df.loc[indices_nulos_cat])

Se encontraron 1 filas con Producto nula.

--- FILAS ANTES DE LA LIMPIEZA (Solo las afectadas) ---
    ID  Factura                Fecha Producto    Categoría  Ventas  \
31  32  FS-2008  2026-02-14 14:15:00      NaN  Desconocido     0.0

    Precio Unitario  Total Ventas Región
31              NaN           0.0    sur

--- FILAS DESPUÉS DE LA LIMPIEZA (Mismos índices) ---
    ID  Factura                Fecha     Producto    Categoría  Ventas  \
31  32  FS-2008  2026-02-14 14:15:00  Desconocido  Desconocido     0.0

    Precio Unitario  Total Ventas Región
31              NaN           0.0    sur

**Reglas de eliminación de filas**

In [ ]:
# Regla, si no posee 'Total Venta's y 'Ventas' se elimina regitro
df = df.dropna(subset=["Total Ventas", "Ventas"])
    # dropna() -> Elimina filas o columnas con valores nulos.
    # subset=["Total Ventas", "Ventas"] -> Solo considera estas columnas para identificar filas con valores nulos. Si alguna de estas columnas tiene un NaN, la fila se eliminará

# Borra filas que tengan menos de 3 columnas con datos válidos
# df.dropna(thresh=3, inplace=True)

# Regla, si no posee 'ID' o 'Producto' se elimina registro (CUIDADO)
# df = df.dropna(subset=['ID', 'Producto'])

**Validacion Final**

In [ ]:
row_null = df[df.isnull().any(axis=1)]
display(row_null)
print("____"*10)
print("\nNulos restantes:")
print(df.isnull().sum())

,ID,Factura,Fecha,Producto,Categoría,Ventas,Precio Unitario,Total Ventas,Región
31,32,FS-2008,2026-02-14 14:15:00,Desconocido,Desconocido,0.0,NaN,0.0,sur

________________________________________

Nulos restantes:
ID                 0
Factura            0
Fecha              0
Producto           0
Categoría          0
Ventas             0
Precio Unitario    1
Total Ventas       0
Región             0
dtype: int64

**Eliminación de filas MANUAL**

In [ ]:
# Se eliminara la fila de ID 32 porque no tiene información relevante,
# ni siquiera el producto. No se puede inferir nada útil de esa fila, y podría distorsionar análisis futuros.
# Ademas no porsee 'Ventas' ni 'Total Ventas', lo que no aporta al análisis. 

# Eliminamos la fila por su etiqueta de índice

# indice del registro a eliminar
indice_a_eliminar = df[df["ID"] == 32].index
df = df.drop(indice_a_eliminar) #.drop() elimina la fila por su índice!

# "Mantén todas las filas donde el ID no sea 32"
# df = df[df["ID"] != 32] # Elimina la fila donde la columna 'ID' es igual a 32

**FIANLIZADA LA LIMPIEZA DE DATOS, AHORA PASAMOS A LA EXPLORACIÓN DE LOS DATOS.**

In [ ]:
print("#########"*10)
print("------- Número de valores únicos por columna Antes y Despues:---------")
valores_unicos_despues_de_limpieza = df.nunique().sort_values()

comparacion = pd.concat(
    [valores_unicos_antes_de_limpieza, valores_unicos_despues_de_limpieza],
    axis=1
)

comparacion.columns = ["Antes", "Después"]
comparacion["Diferencia"] = comparacion["Después"] - comparacion["Antes"]
# comparacion[comparacion["Diferencia"] != 0]


display(comparacion)

print("_____"*18)

##########################################################################################
------- Número de valores únicos por columna Antes y Despues:---------

                 Antes  Después  Diferencia
Región               4        4           0
Categoría            5        5           0
Ventas              13       15           2
Producto            15       14          -1
Total Ventas        22       22           0
Precio Unitario     22       22           0
ID                  32       27          -5
Fecha               32       28          -4
Factura             32       28          -4

__________________________________________________________________________________________

In [ ]:
# Datos estadisticos por Separados por Columna 
# .median()
# .mode()
# .mean()
# .sum()
# .count()
# .max()
# .min()
# .quantile()
# .var()
# .std()
# .value_counts() # Cuenta la frecuencia de cada valor único en una columna. Es útil para columnas categóricas o discretas, ya que muestra cuántas veces aparece cada valor en la columna.
# .unique() # Devuelve un array de los valores únicos presentes en una columna. Es útil para entender la diversidad de valores en una columna, especialmente en columnas categóricas.
# .nunique() # Devuelve el número de valores únicos en una columna. Es útil para obtener una rápida visión general de la cantidad de categorías o valores distintos en una columna.
# .describe() # VER ARRIBA

# Calculo de mediana de la columna 'Ventas'
mediana_ventas = df['Ventas'].median()
print("\n-------- Mediana de la columna 'Ventas': ------- \n")
print(f"La mediana de la columna 'Ventas' es: {mediana_ventas}")
print("______"*10)

# Calculo de moda de la columna 'Categoría'
moda_categoria = df['Categoría'].mode()[0]
print("\n-------- Moda de la columna 'Categoría': ------- \n")
print(f"La moda de la columna 'Categoría' es: {moda_categoria}")
# .mode()[1] es para obtener la segunda moda si existe
print("______"*10)

# Calculo de rango de la columna 'Ventas'
# Rango = Valor máximo - Valor mínimo 
# .range() no existe como método directo en pandas, pero se puede calcular restando el valor mínimo al valor máximo de una columna.
rango_ventas = df['Ventas'].max() - df['Ventas'].min()
print("\n-------- Rango de la columna 'Ventas': ------- \n")
print(f"El rango de la columna 'Ventas' es: {rango_ventas}")
print("______"*10)   

# Cuartiles de la columna 'Total Ventas'
cuartiles_total_ventas = df['Total Ventas'].quantile([0.25, 0.5, 0.75])
print("\n-------- Cuartiles de la columna 'Total Ventas': ------- \n")
print("Cuartiles de la columna 'Total Ventas':")
print(cuartiles_total_ventas)
print("______"*10)

# Calculo de media de la columna 'Ventas'
mean_ventas = df['Ventas'].mean()
print(f" --- La media de la columna 'Ventas' es: {mean_ventas:.2f}")
# Salida: La media de la columna 'Ventas' es: 18.30
print("______"*10)

# Calculo de suma de la columna 'Ventas'
suma_ventas = df['Ventas'].sum()
print(f" --- La suma de la columna 'Ventas' es: {suma_ventas}")
# Salida: La suma de la columna 'Ventas' es: 183
print("______"*10)

# Calculo de conteo de la columna 'Ventas'
conteo_ventas = df['Ventas'].count()
print(f" --- El conteo de la columna 'Ventas' es: {conteo_ventas}")
# Salida: El conteo de la columna 'Ventas' es: 10

-------- Mediana de la columna 'Ventas': -------

La mediana de la columna 'Ventas' es: 11.0
____________________________________________________________

-------- Moda de la columna 'Categoría': -------

La moda de la columna 'Categoría' es: accesorios
____________________________________________________________

-------- Rango de la columna 'Ventas': -------

El rango de la columna 'Ventas' es: 40.0
____________________________________________________________

-------- Cuartiles de la columna 'Total Ventas': -------

Cuartiles de la columna 'Total Ventas':
0.25    1006.25
0.50    2470.00
0.75    5400.00
Name: Total Ventas, dtype: float64
____________________________________________________________
 --- La media de la columna 'Ventas' es: 13.89
____________________________________________________________
 --- La suma de la columna 'Ventas' es: 389.0
____________________________________________________________
 --- El conteo de la columna 'Ventas' es: 28

In [ ]:
print("\n ################################################## ")
# Calculo de varianza de la columna 'Precio Unitario'
varianza_precio = df['Precio Unitario'].var()
print("\n-------- Varianza de la columna 'Precio Unitario': ------- \n")
print(f"La varianza de la columna 'Precio Unitario' es: {varianza_precio:.2f}")
print("______"*10)
# Calculo de desviación estándar de la columna 'Total Ventas'
desviacion_total_ventas = df['Total Ventas'].std()
print("\n-------- Desviación estándar de la columna 'Total Ventas': ------- \n")
print(f"La desviación estándar de la columna 'Total Ventas' es: {desviacion_total_ventas:.2f}")
print("______"*10)   
# Calculo de coeficiente de variación de la columna 'Precio Unitario'
coeficiente_variacion_precio = (df['Precio Unitario'].std() / df['Precio Unitario'].mean()) * 100 
print("\n-------- Coeficiente de variación de la columna 'Precio Unitario': ------- \n")
print(f"El coeficiente de variación de la columna 'Precio Unitario' es: {coeficiente_variacion_precio:.2f}%")   
print("______"*10)

 ##################################################

-------- Varianza de la columna 'Precio Unitario': -------

La varianza de la columna 'Precio Unitario' es: 120695.07
____________________________________________________________

-------- Desviación estándar de la columna 'Total Ventas': -------

La desviación estándar de la columna 'Total Ventas' es: 5675.85
____________________________________________________________

-------- Coeficiente de variación de la columna 'Precio Unitario': -------

El coeficiente de variación de la columna 'Precio Unitario' es: 91.30%
____________________________________________________________

In [ ]:
# .value_counts() # Cuenta la frecuencia de cada valor único en una columna. Es útil para columnas categóricas o discretas, ya que muestra cuántas veces aparece cada valor en la columna.
# .unique() # Devuelve un array de los valores únicos presentes en una columna. Es útil para entender la diversidad de valores en una columna, especialmente en columnas categóricas.
# .nunique() # Devuelve el número de valores únicos en una columna. Es útil para obtener una rápida visión general de la cantidad de categorías o valores distintos en una columna.
# .describe() # VER ARRIBA

# Contar la frecuencia de cada valor único en la columna 'Categoría'
frecuencia_categoria = df['Categoría'].value_counts()
print("---- Frecuencia de cada valor único en la columna 'Categoría': ----- ")
print(frecuencia_categoria)
print("______"*10)

# Contar el número de valores únicos en la columna 'Región'
num_valores_unicos_region = df['Región'].nunique()
print("\n ---- Número de valores únicos en la columna 'Región': ----- ")
print(f"El número de valores únicos en la columna 'Región' es: {num_valores_unicos_region}")
valores_unicos_region = df['Región'].unique()
print("\n ---- Valores únicos presentes en la columna 'Región': ----- ")
print("Lista de los valores únicos en la columna 'Región' son:") 
print(valores_unicos_region)

print("______"*10)
num_valores_unicos_producto = df['Producto'].nunique()
print("\n ---- Número de valores únicos en la columna 'Producto': ----- ")
print(f"El número de valores únicos en la columna 'Producto' es: {num_valores_unicos_producto}")
# Obtener los valores únicos presentes en la columna 'Producto'
valores_unicos_producto = df['Producto'].unique()
print("\n ---- Lista de valores únicos presentes en la columna 'Producto': ----- ")
print("Los valores únicos en la columna 'Producto' son:")
print(valores_unicos_producto)

---- Frecuencia de cada valor único en la columna 'Categoría': -----
Categoría
accesorios     9
computación    8
oficina        6
electrónica    3
audio          2
Name: count, dtype: int64
____________________________________________________________

 ---- Número de valores únicos en la columna 'Región': -----
El número de valores únicos en la columna 'Región' es: 4

 ---- Valores únicos presentes en la columna 'Región': -----
Lista de los valores únicos en la columna 'Región' son:
<StringArray>
['norte', 'sur', 'este', 'oeste']
Length: 4, dtype: str
____________________________________________________________

 ---- Número de valores únicos en la columna 'Producto': -----
El número de valores únicos en la columna 'Producto' es: 14

 ---- Lista de valores únicos presentes en la columna 'Producto': -----
Los valores únicos en la columna 'Producto' son:
<StringArray>
[     'laptop',     'monitor',     'teclado',      'tablet',   'impresora',
     'escáner',       'mouse', 'auriculares',      'webcam',   'micrófono',
 'silla gamer',  'disco duro',   'cable usb', 'ssd externo']
Length: 14, dtype: str

In [ ]:
# Resumen estadístico de la columna 'Ventas'
resumen_ventas = df['Ventas'].describe()
print("\n ---- Resumen estadístico de la columna 'Ventas': ----- \n")
print(resumen_ventas)
print("______"*10)

 ---- Resumen estadístico de la columna 'Ventas': -----

count    28.000000
mean     13.892857
std       9.507655
min       0.000000
25%       8.000000
50%      11.000000
75%      18.000000
max      40.000000
Name: Ventas, dtype: float64
____________________________________________________________

In [ ]:
#####otros métodos estadísticos útiles:
# .cov() # Covarianza entre dos columnas, pero no es un método directo para una sola columna. Se utiliza para calcular la covarianza entre dos columnas numéricas en un DataFrame.
            # Nota: La covarianza mide cómo dos variables cambian juntas. Si la covarianza es positiva, significa que ambas variables tienden a aumentar o disminuir juntas. Si es negativa, significa que una variable tiende a aumentar mientras la otra disminuye.
# .corr() # Correlación entre dos columnas, pero no es un método directo para una sola columna. Se utiliza para calcular la correlación entre dos columnas numéricas en un DataFrame.
            # Nota: La correlación mide la fuerza y la dirección de la relación lineal entre dos variables. El coeficiente de correlación varía entre -1 y 1, donde 1 indica una correlación positiva perfecta, -1 indica una correlación negativa perfecta y 0 indica que no hay correlación.
            # la correlación es una medida estandarizada de la covarianza, lo que significa que se encuentra en un rango específico (-1 a 1) y no depende de las unidades de medida de las variables.
# .skew() # Asimetría de la distribución de una columna numérica. Un valor de asimetría positivo indica que la distribución tiene una cola más larga hacia la derecha, mientras que un valor negativo indica una cola más larga hacia la izquierda. Un valor cercano a cero sugiere una distribución simétrica. Nota: normalmente, una distribución normal tiene una asimetría de aproximadamente 0.
# .kurt() # Curtosis de la distribución de una columna numérica. La curtosis mide la "agudeza" de la distribución. Un valor de curtosis positivo indica una distribución con colas más pesadas y un pico más alto que una distribución normal, mientras que un valor negativo indica una distribución con colas más ligeras y un pico más bajo. Un valor cercano a cero sugiere una distribución similar a la normal.

In [ ]:
# .iloc() Se basa en la posición (número de índice).

# Seleccionar la primera fila del DataFrame utilizando .iloc()
first_row = df.iloc[0] 
print("-------- Primera fila del DataFrame utilizando .iloc(): ------- ")
print(first_row) # Agrupa los valores de la primera fila en una Serie de pandas, donde el índice de la Serie corresponde a los nombres de las columnas del DataFrame.
print("______"*10)

# Seleccionar el tercer valor de la columna 'Total Ventas' utilizando .iloc()
tercer_valor_total_ventas = df['Total Ventas'].iloc[2]
print("-------- Tercer valor de la columna 'Total Ventas' utilizando .iloc(): ------- ")
print(f"El tercer valor de la columna 'Total Ventas' es: {tercer_valor_total_ventas}")
print("______"*10)

# Seleccionar las primeras tres filas del DataFrame utilizando .iloc()
first_three_rows = df.iloc[:3]
print("-------- Primeras tres filas del DataFrame utilizando .iloc(): ------- ")
print(first_three_rows) # Devuelve un nuevo DataFrame que contiene las primeras tres filas del DataFrame original.
# Seleccionar las ultimas tres filas del DataFrame utilizando .iloc()
last_three_rows = df.iloc[-3:]
print("-------- Últimas tres filas del DataFrame utilizando .iloc(): ------- ")
print(last_three_rows)
print("______"*10)

# Seleccionar las filas del índice 2 al 4 del DataFrame utilizando .iloc()
first_five_row = df.iloc[2:5]
print("-------- Filas del índice 2 al 4 del DataFrame utilizando .iloc(): ------- ")
print(first_five_row)

-------- Primera fila del DataFrame utilizando .iloc(): -------
ID                                   1
Factura                        FN-1001
Fecha              2026-01-02 10:15:00
Producto                        laptop
Categoría                  electrónica
Ventas                            15.0
Precio Unitario                 1200.0
Total Ventas                   18000.0
Región                           norte
Name: 0, dtype: object
____________________________________________________________
-------- Tercer valor de la columna 'Total Ventas' utilizando .iloc(): -------
El tercer valor de la columna 'Total Ventas' es: 1200.0
____________________________________________________________
-------- Primeras tres filas del DataFrame utilizando .iloc(): -------
   ID  Factura                Fecha Producto    Categoría  Ventas  \
0   1  FN-1001  2026-01-02 10:15:00   laptop  electrónica    15.0
1   2  FS-2001  2026-01-04 15:40:00  monitor  computación     8.0
2   3  FN-1002  2026-01-05 09:20:00  teclado   accesorios    25.0

   Precio Unitario  Total Ventas Región
0           1200.0       18000.0  norte
1            500.0        4000.0    sur
2             50.0        1200.0  norte
-------- Últimas tres filas del DataFrame utilizando .iloc(): -------
    ID  Factura                Fecha     Producto    Categoría  Ventas  \
28  30  FO-4007  2026-02-11 15:20:00    cable usb   accesorios    10.0
29  30  FE-3006  2026-02-12 09:45:00    cable usb   accesorios    10.0
30  31  FN-1011  2026-02-13 12:00:00  ssd externo  computación     0.0

    Precio Unitario  Total Ventas Región
28             80.0         800.0  oeste
29             80.0         800.0   este
30            150.0           0.0  norte
____________________________________________________________
-------- Filas del índice 2 al 4 del DataFrame utilizando .iloc(): -------
   ID  Factura                Fecha Producto    Categoría  Ventas  \
2   3  FN-1002  2026-01-05 09:20:00  teclado   accesorios    25.0
3   4  FE-3001  2026-01-08 14:10:00   laptop  electrónica    10.0
4   5  FO-4001  2026-01-10 11:30:00   tablet  computación    20.0

   Precio Unitario  Total Ventas Región
2             50.0        1200.0  norte
3           1100.0       11000.0   este
4            700.0       14000.0  oeste

In [ ]:
# Crear un subconjunto del DataFrame utilizando .iloc() para seleccionar las primeras tres filas y las primeras dos columnas.
subset = df.iloc[:3, :6]
print(subset)

print("______"*10)
# Crear un subconjunto del DataFrame para seleccionar las ultimas tres filas y la columna ID, Producto, Total Ventas y Región .
subset_last_three_rows = df.iloc[-3:, [1, 3, 4]] # Selecciona las últimas tres filas y las columnas ID, Producto, Total Ventas y Región
print(subset_last_three_rows)
print("______"*10)

# retail_value = df.iloc[1, 3] # no da mayor info
retail_value = df.iloc[1, [3, 5]]
print("-------- Valor de la fila 1 y columna 'producto' y 'Ventas' utilizando .iloc(): ------- ")
print(retail_value)
# Acceso por posición (menos legible)
print(f"El valor del producto es '{retail_value.iloc[0]}' y las ventas son '{retail_value.iloc[1]}'")
# Acceso por nombre (más legible)
print(f"Producto: {retail_value['Producto']}, Ventas: {retail_value['Ventas']} unidades")
# Acceso por índice genera error porque retail_value es una Serie, no un DataFrame o una lista.
# ERROR -  NO VALIDO  # Series se parecen a las listas, tienen sus propias reglas de etiqueta.
# print(f"El valor del producto es '{retail_value[0]}' y las ventas son '{retail_value[1]}'") ### ERROR # Busca la etiqueta llamada 0

   ID  Factura                Fecha Producto    Categoría  Ventas
0   1  FN-1001  2026-01-02 10:15:00   laptop  electrónica    15.0
1   2  FS-2001  2026-01-04 15:40:00  monitor  computación     8.0
2   3  FN-1002  2026-01-05 09:20:00  teclado   accesorios    25.0
____________________________________________________________
    Factura     Producto    Categoría
28  FO-4007    cable usb   accesorios
29  FE-3006    cable usb   accesorios
30  FN-1011  ssd externo  computación
____________________________________________________________
-------- Valor de la fila 1 y columna 'producto' y 'Ventas' utilizando .iloc(): -------
Producto    monitor
Ventas          8.0
Name: 1, dtype: object
El valor del producto es 'monitor' y las ventas son '8.0'
Producto: monitor, Ventas: 8.0 unidades

In [ ]:
# crear una nueva columna 'IVA' y 'Precio con IVA' que sea el resultado de dividir
  
# df['IVA'] = df['Total Ventas'] * 0.19  # Suponiendo un IVA del 19%
df['IVA'] = df['Total Ventas'].apply(lambda x: x * 0.19 if pd.notnull(x) else np.nan)
df['Precio con IVA'] = df['Total Ventas'] + df['IVA']

df['ventaMayor5mil'] = df['Total Ventas'] > 5000
 

def categorize_price(price):
  if price >= 180:
    return 'High'
  elif price < 180 and price > 90:
    return 'Medium'
  else:
    return 'Low'

df['PriceCategory'] = df['Precio Unitario'].apply(categorize_price)
print(df.head(5))

   ID  Factura                Fecha Producto    Categoría  Ventas  \
0   1  FN-1001  2026-01-02 10:15:00   laptop  electrónica    15.0
1   2  FS-2001  2026-01-04 15:40:00  monitor  computación     8.0
2   3  FN-1002  2026-01-05 09:20:00  teclado   accesorios    25.0
3   4  FE-3001  2026-01-08 14:10:00   laptop  electrónica    10.0
4   5  FO-4001  2026-01-10 11:30:00   tablet  computación    20.0

   Precio Unitario  Total Ventas Región     IVA  Precio con IVA  \
0           1200.0       18000.0  norte  3420.0         21420.0
1            500.0        4000.0    sur   760.0          4760.0
2             50.0        1200.0  norte   228.0          1428.0
3           1100.0       11000.0   este  2090.0         13090.0
4            700.0       14000.0  oeste  2660.0         16660.0

   ventaMayor5mil PriceCategory
0            True          High
1           False          High
2           False           Low
3            True          High
4            True          High

# Filtos

In [ ]:
#Filtrar ventas en la región norte, solo imprimir [Factura, Producto, Ventas, Ingreso Total 
ventas_norte = df[df['Región'] == 'norte']
print("Ventas en la región NORTE:")
print(ventas_norte[['Factura', 'Producto', 'Ventas', 'Total Ventas']].head(5))

Ventas en la región NORTE:
    Factura   Producto  Ventas  Total Ventas
0   FN-1001     laptop    15.0       18000.0
2   FN-1002    teclado    25.0        1200.0
5   FN-1003  impresora     5.0        2000.0
9   FN-1004     tablet    18.0       13500.0
13  FN-1005      mouse    35.0         875.0

In [ ]:
# Filtar todas las  ventas menores a 10, solo imprimir [Factura, Producto, Ventas, Ingreso Total]
ventas_menores_10 = df[df['Ventas'] < 10]
print("Ventas menores a 10 unidades:")
print(ventas_menores_10[['Factura', 'Producto', 'Ventas', 'Total Ventas']])

Ventas menores a 10 unidades:
    Factura     Producto  Ventas  Total Ventas
1   FS-2001      monitor     8.0        4000.0
5   FN-1003    impresora     5.0        2000.0
6   FO-4002      escáner     5.0        1050.0
11  FE-3003    impresora     7.0        2940.0
20  FN-1008    micrófono     8.0        3200.0
21  FO-4006      escáner     5.0        1050.0
23  FE-3005   disco duro     2.0         240.0
30  FN-1011  ssd externo     0.0           0.0

In [ ]:
# Filtrar ventas de LAPTO con cantidad mayor a 5 unidades, solo imprimir [Factura, Producto, Ventas, Ingreso Total]
ventas_impresora_mayor_5 = df[(df['Producto'] == 'impresora') & (df['Ventas'] >= 10)]
print("Ventas de impresora con cantidad mayor a 5 unidades:")
print(ventas_impresora_mayor_5[['Factura', 'Producto', 'Ventas', 'Total Ventas']])
# menor a 5 unidades
ventas_impresora_menor_5 = df[(df['Producto'] == 'impresora') & (df['Ventas'] < 10)]
print("Ventas de impresora con cantidad menor a 5 unidades:")
print(ventas_impresora_menor_5[['Factura', 'Producto', 'Ventas', 'Total Ventas']])

Ventas de impresora con cantidad mayor a 5 unidades:
    Factura   Producto  Ventas  Total Ventas
18  FS-2004  impresora    12.0        5400.0
Ventas de impresora con cantidad menor a 5 unidades:
    Factura   Producto  Ventas  Total Ventas
5   FN-1003  impresora     5.0        2000.0
11  FE-3003  impresora     7.0        2940.0

In [ ]:
# # validar si Norte es lider es ventas (Total Ventas).
# total_ventas = df['Total Ventas'].sum()
# ventas_norte = df[df['Región'] == 'norte']['Total Ventas'].sum()
# ventas_sur = df[df['Región'] == 'sur']['Total Ventas'].sum()
# ventas_este = df[df['Región'] == 'este']['Total Ventas'].sum
# ventas_norte = df[df['Región'] == 'norte']['Total Ventas'].sum()

# porcentaje_norte = (ventas_norte / total_ventas * 100) if total_ventas > 0 else 0
# porcentaje_sur = (ventas_sur / total_ventas * 100) if total_ventas > 0 else 0
# porcentaje_este = (ventas_este / total_ventas * 100) if total_ventas > 0 else 0
# porcentaje_oeste = (ventas_oeste / total_ventas * 100) if total_ventas > 0 else 0

# print(f"Ventas de Norte: {ventas_norte}")
# print(f"Porcentaje de ventas de Norte: {porcentaje_norte:.2f}%")
# print(f"¿Norte lidera?")

In [ ]:
# Ventas generadas los primeros 15 dias de Enero
ventas_enero = df[df['Factura'].str.contains('2026-01')]
print("Ventas generadas en Enero:")
print(ventas_enero[['Factura', 'Producto', 'Ventas', 'Total Ventas']])

Ventas generadas en Enero:
Empty DataFrame
Columns: [Factura, Producto, Ventas, Total Ventas]
Index: []

In [ ]:
# sales_Ene_2026

#### **Manipulacion, consulta, etc de datos tipo datetime para el manejo de fechas (o Time Series)**

In [ ]:
# Convertimos la columna a objeto datetime
df['Fecha'] = pd.to_datetime(df['Fecha'])

# Verificamos el cambio
print(df['Fecha'].dtype)
# Debería decir: datetime64[ns]

datetime64[us]

In [ ]:
# Una vez que es datetime, puedes extraer partes de la fecha sin usar complicados filtros de texto.

# Crear nuevas columnas para análisis temporal
df['Año'] = df['Fecha'].dt.year
df['Mes'] = df['Fecha'].dt.month
df['Dia_Semana'] = df['Fecha'].dt.day_name() # Lunes, Martes...
df['Hora'] = df['Fecha'].dt.hour

print(df[['Fecha', 'Mes', 'Dia_Semana', 'Hora']].head())

                Fecha  Mes Dia_Semana  Hora
0 2026-01-02 10:15:00    1     Friday    10
1 2026-01-04 15:40:00    1     Sunday    15
2 2026-01-05 09:20:00    1     Monday     9
3 2026-01-08 14:10:00    1   Thursday    14
4 2026-01-10 11:30:00    1   Saturday    11

In [ ]:
# ¿Cuál es el día de la semana con más ventas?
# A veces las empresas descubren que los lunes venden más que los sábados.
ventas_por_dia = df.groupby(df['Fecha'].dt.day_name())['Total Ventas'].sum().sort_values(ascending=False)
print(ventas_por_dia)

Fecha
Saturday     37900.0
Friday       32775.0
Thursday     23475.0
Sunday       16460.0
Tuesday      10650.0
Monday       10340.0
Wednesday     3640.0
Name: Total Ventas, dtype: float64

In [ ]:
# ¿En qué franja horaria se factura más?
# Útil para saber cuándo poner más personal en el Call Center.
# Creamos rangos de horas
df['Franja_Horaria'] = pd.cut(df['Fecha'].dt.hour,   # ERROR AttributeError: Can only use .dt accessor with datetimelike values
                              bins=[0, 12, 18, 24], 
                              labels=['Mañana', 'Tarde', 'Noche'])

ventas_franja = df.groupby('Franja_Horaria')['Total Ventas'].sum()
print(ventas_franja)

Franja_Horaria
Mañana    74530.0
Tarde     60710.0
Name: Total Ventas, dtype: float64

In [ ]:
# Seleccionar solo ventas de la primera quincena de enero
primera_quincena = df[df['Fecha'].dt.day <= 15]
print(" --- Ventas de la primera quincena de enero:")
print(primera_quincena[['Fecha', 'Producto', 'Ventas', 'Total Ventas']].head(10))

# O ventas de un mes específico (si tuvieras datos de todo el año)
ventas_enero = df[df['Fecha'].dt.month == 1]
print("\n --- Ventas de enero:")
print(ventas_enero[['Fecha', 'Producto', 'Ventas', 'Total Ventas']].head(10))

 --- Ventas de la primera quincena de enero:
                 Fecha   Producto  Ventas  Total Ventas
0  2026-01-02 10:15:00     laptop    15.0       18000.0
1  2026-01-04 15:40:00    monitor     8.0        4000.0
2  2026-01-05 09:20:00    teclado    25.0        1200.0
3  2026-01-08 14:10:00     laptop    10.0       11000.0
4  2026-01-10 11:30:00     tablet    20.0       14000.0
5  2026-01-12 16:45:00  impresora     5.0        2000.0
6  2026-01-13 08:55:00    escáner     5.0        1050.0
7  2026-01-14 13:20:00      mouse    40.0         800.0
8  2026-01-15 17:05:00    monitor    12.0        5400.0
21 2026-02-01 10:00:00    escáner     5.0        1050.0

 --- Ventas de enero:
                Fecha   Producto  Ventas  Total Ventas
0 2026-01-02 10:15:00     laptop    15.0       18000.0
1 2026-01-04 15:40:00    monitor     8.0        4000.0
2 2026-01-05 09:20:00    teclado    25.0        1200.0
3 2026-01-08 14:10:00     laptop    10.0       11000.0
4 2026-01-10 11:30:00     tablet    20.0       14000.0
5 2026-01-12 16:45:00  impresora     5.0        2000.0
6 2026-01-13 08:55:00    escáner     5.0        1050.0
7 2026-01-14 13:20:00      mouse    40.0         800.0
8 2026-01-15 17:05:00    monitor    12.0        5400.0
9 2026-01-16 09:15:00     tablet    18.0       13500.0

# PREGUNTAS TIPO RETO:::::

In [ ]:
############## ¿Cuál es la cantidad total de productos vendidos? #######################
cantidad_total_productos = df['Ventas'].sum()
# print("La cantidad total de productos vendidos es:", cantidad_total_productos)
print(cantidad_total_productos)

389.0

In [ ]:
# C. Ventas Acumuladas en el Tiempo (Tendencia)
# Esto sirve para ver si el negocio crece o cae día tras día.

ventas_diarias = df.groupby(df['Fecha'].dt.date)['Total Ventas'].sum()
# AttributeError: Can only use .dt accessor with datetimelike values

In [ ]:
"""
¿Cuál es el ticket promedio de producto por categoría? //¿Precio unitario promedio por categoría?
¿Generar un avisión general de cómo varían los precios unitarios en diferentes productos, y por regiones?
¿Qué productos son más caros en cada región?
¿Cuál es la participación de ventas (market share) por región? //Permite ver cuál región es el motor de la empresa.
¿Cuál es la mezcla de categorías (product mix) por cada región? //Revela si en el Norte se vende algo distinto al Sur.
¿Cómo crear subconjuntos de datos (filtros) por zona geográfica? // para reportes específicos a cada gerente regional.
¿Cuál es la relación entre el volumen de unidades y el ingreso total por producto? //Identifica productos que se venden poco pero a gran precio.
¿Categoría con la relacion Total Ventas/ Ventas? //Identifica categorías que generan mucho ingreso a pesar de vender pocas unidades.
¿Cómo evolucionaron las ventas diarias durante la primera quincena de enero?
¿Cuál es el producto que genera el mayor ingreso con el menor número de unidades vendidas?
¿Cuál es el resumen estadístico de ventas y precios para el producto 'Teclado' en todas las regiones?
¿Existen saltos o inconsistencias en la secuencia numérica de las facturas por cada prefijo regional?
"""

"\n¿Cuál es el ticket promedio de producto por categoría? //¿Precio unitario promedio por categoría?\n¿Generar un avisión general de cómo varían los precios unitarios en diferentes productos, y por regiones?\n¿Qué productos son más caros en cada región?\n¿Cuál es la participación de ventas (market share) por región? //Permite ver cuál región es el motor de la empresa.\n¿Cuál es la mezcla de categorías (product mix) por cada región? //Revela si en el Norte se vende algo distinto al Sur.\n¿Cómo crear subconjuntos de datos (filtros) por zona geográfica? // para reportes específicos a cada gerente regional.\n¿Cuál es la relación entre el volumen de unidades y el ingreso total por producto? //Identifica productos que se venden poco pero a gran precio.\n¿Categoría con la relacion Total Ventas/ Ventas? //Identifica categorías que generan mucho ingreso a pesar de vender pocas unidades.\n¿Cómo evolucionaron las ventas diarias durante la primera quincena de enero?\n¿Cuál es el producto que genera el mayor ingreso con el menor número de unidades vendidas?\n¿Cuál es el resumen estadístico de ventas y precios para el producto 'Teclado' en todas las regiones?\n¿Existen saltos o inconsistencias en la secuencia numérica de las facturas por cada prefijo regional?\n"

In [ ]:
# ¿Calcular por Región los Ingresos Totales Recalculados a partir de Ventas y Precio Unitario?

# 1. Definimos la función adaptada a tus nombres de columnas
def calcular_ingreso_total(grupo):
    # Multiplicamos la columna de unidades por la de precio y sumamos el resultado
    return (grupo['Ventas'] * grupo['Precio Unitario']).sum()

# 2. Aplicamos el groupby por 'Región'
# En lugar de 'Country', usamos 'Región'
ingreso_por_region = df.groupby('Región').apply(calcular_ingreso_total, include_groups=False)

print("Ingreso Total Recalculado por Región:")
print(ingreso_por_region)

Ingreso Total Recalculado por Región:
Región
este     25980.0
norte    41900.0
oeste    27900.0
sur      39510.0
dtype: float64

In [ ]:
# ¿Cual es el top 3 de mejores Regiones en ingresos totales ( Pero indicar en otra columna el total de ventas por región)? 
# 1. Calculamos el ingreso total por región usando la función que definimos antes
ingreso_por_region = df.groupby('Región').apply(calcular_ingreso_total, include_groups=False)   
# 2. Obtenemos el total de ventas por región
ventas_por_region = df.groupby('Región')['Ventas'].sum()
# 3. Combinamos ambos resultados en un DataFrame
resultados = ingreso_por_region.to_frame(name='Ingreso Total').join(ventas_por_region.to_frame(name='Ventas Totales'))
# 4. Obtenemos el top 3 de regiones por ingreso total
top_3_regiones = resultados.sort_values(by='Ingreso Total', ascending=False).head(3)
print("Top 3 de Regiones por Ingreso Total Recalculado:")
print(top_3_regiones)
print("____"*10)

# ¿Cual es el top 3 de peores Regiones en ingresos totales ( Pero indicar en otra columna el total de ventas por región)? 
top_3_peores_regiones = resultados.sort_values(by='Ingreso Total', ascending=True).head(3)
print("Top 3 de Peores Regiones por Ingreso Total Recalculado:")
print(top_3_peores_regiones)

Top 3 de Regiones por Ingreso Total Recalculado:
        Ingreso Total  Ventas Totales
Región
norte         41900.0           151.0
sur           39510.0            82.0
oeste         27900.0            72.0
________________________________________
Top 3 de Peores Regiones por Ingreso Total Recalculado:
        Ingreso Total  Ventas Totales
Región
este          25980.0            84.0
oeste         27900.0            72.0
sur           39510.0            82.0

In [ ]:
# Calcular el ingreso total por producto (Ventas * Precio Unitario) y luego agrupar por categoría para obtener el total por categoría.
df['Ingreso Total'] = df['Ventas'] * df['Precio Unitario']
ingreso_por_categoria = df.groupby('Categoría')['Ingreso Total'].sum()
print("\nIngreso Total por Categoría:")
print(ingreso_por_categoria)

Ingreso Total por Categoría:
Categoría
accesorios      9610.0
audio           7200.0
computación    52140.0
electrónica    49700.0
oficina        16640.0
Name: Ingreso Total, dtype: float64

In [ ]:
# ¿Cuál es la categoría con mayor total de ventas acumuladas?
# categoria_mayor_ventas = df.groupby('Categoría')['Total Ventas'].sum().idxmax()
ventas_por_cat = df.groupby('Categoría')['Total Ventas'].sum()
# Nombre de la categoría ganadora
categoria_top = ventas_por_cat.idxmax() 
# Cuánto vendió esa categoría (opcional)
valor_top = ventas_por_cat.max()
print(f"La ganadora es '{categoria_top}' con un total de ${valor_top}")

La ganadora es 'computación' con un total de $52140.0

In [ ]:
# Mostrar solo los productos con un precio unitario mayor a 500 Y SIN DECIMALES
productos_precio_alto = df[df['Precio Unitario'] > 500].copy()
productos_precio_alto['Precio Unitario'] = productos_precio_alto['Precio Unitario'].astype(int)
productos_precio_alto['Total Ventas'] = productos_precio_alto['Total Ventas'].astype(int)
# print("Productos con un precio unitario mayor a 500:")
print(productos_precio_alto)

    ID  Factura               Fecha Producto    Categoría  Ventas  \
0    1  FN-1001 2026-01-02 10:15:00   laptop  electrónica    15.0
3    4  FE-3001 2026-01-08 14:10:00   laptop  electrónica    10.0
4    5  FO-4001 2026-01-10 11:30:00   tablet  computación    20.0
9   10  FN-1004 2026-01-16 09:15:00   tablet  computación    18.0
14  15  FS-2003 2026-01-24 16:30:00   laptop  electrónica    18.0
15  16  FE-3004 2026-01-25 09:50:00   tablet  computación    15.0

    Precio Unitario  Total Ventas Región     IVA  Precio con IVA  \
0              1200         18000  norte  3420.0         21420.0
3              1100         11000   este  2090.0         13090.0
4               700         14000  oeste  2660.0         16660.0
9               750         13500  norte  2565.0         16065.0
14             1150         20700    sur  3933.0         24633.0
15              680         10200   este  1938.0         12138.0

    ventaMayor5mil PriceCategory   Año  Mes Dia_Semana  Hora Franja_Horaria  \
0             True          High  2026    1     Friday    10         Mañana
3             True          High  2026    1   Thursday    14          Tarde
4             True          High  2026    1   Saturday    11         Mañana
9             True          High  2026    1     Friday     9         Mañana
14            True          High  2026    1   Saturday    16          Tarde
15            True          High  2026    1     Sunday     9         Mañana

    Ingreso Total
0         18000.0
3         11000.0
4         14000.0
9         13500.0
14        20700.0
15        10200.0

In [ ]:
# Calcular el precio promedio de todos los productos.
precio_promedio = df['Precio Unitario'].mean()
# print("El precio promedio de todos los productos es:", precio_promedio
print(precio_promedio)

380.5357142857143

In [ ]:

# Se crea una nueva columna llamada "Precio Actualizado" que aumente los precios en un 10%.
df['Precio Actualizado'] = df['Precio Unitario'] * 1.1
# print(df.head())

#Generar una tabla, Producto  Precio Unitario  Precio Actualizado:   #### MUY RECOMENDABLE EL USO DE .copy #### FORMA SEGURA ####
tabla_precio_actualizado = df[['Producto', 'Precio Unitario', 'Precio Actualizado']].copy()
# print(tabla_precio_actualizado)

# quitar decimales a: Precio Unitario
tabla_precio_actualizado['Precio Unitario'] = tabla_precio_actualizado['Precio Unitario'].astype(int)
print(tabla_precio_actualizado)

       Producto  Precio Unitario  Precio Actualizado
0        laptop             1200              1320.0
1       monitor              500               550.0
2       teclado               50                55.0
3        laptop             1100              1210.0
4        tablet              700               770.0
5     impresora              400               440.0
6       escáner              210               231.0
7         mouse               20                22.0
8       monitor              450               495.0
9        tablet              750               825.0
10      teclado               55                60.5
11    impresora              420               462.0
12  auriculares               80                88.0
13        mouse               25                27.5
14       laptop             1150              1265.0
15       tablet              680               748.0
16      monitor              480               528.0
17      teclado               60                66.0
18    impresora              450               495.0
19       webcam               85                93.5
20    micrófono              400               440.0
21      escáner              210               231.0
22  silla gamer              350               385.0
23   disco duro              120               132.0
27    micrófono              400               440.0
28    cable usb               80                88.0
29    cable usb               80                88.0
30  ssd externo              150               165.0

# Insight  
En el mundo de los datos, un Insight (o hallazgo) es el momento "¡Ajá!". No es solo ver un número, sino entender qué significa ese número para el negocio y qué acción debes tomar al respecto.


Dato: "Vendimos 500 unidades en la región Sur". (Es un hecho crudo).
Información: "Las ventas en el Sur cayeron un 20% respecto al mes pasado". (Es el dato con contexto).
Insight: "Las ventas en el Sur cayeron porque los precios subieron justo cuando la competencia lanzó una promoción; sin embargo, los clientes más fieles siguieron comprando". (Es la comprensión profunda).
Acción: "Debemos crear un programa de lealtad en el Sur para proteger a los clientes fieles antes de bajar los precios".

### FORMULA

Un insight es: hallazgo + evidencia + acción o hipótesis:

hallazgo: Bogotá es la ciudad líder

Evidencia: Aporta 42% de ventas

Acción: Analizar qué hace bien Bogotá y replicarlo en otras ciudades

### 📝 Nota de Estudio:

#### 1. ¿Por qué existe el `NaN` y qué tipo de dato es?

`NaN` (Not a Number) técnicamente es un número.
* ¿Por qué es un número? En computación, para que una columna de precios sea rápida de procesar, todos los elementos deben ser del mismo tipo (ej. `float64`). Si pusiéramos un string, la columna se volvería lenta.
`type(np.nan)`, es `<class 'float'>`. Es un "marcador de posición" numérico que dice: *"Aquí debería ir un número, pero no lo tenemos"*.

#### 2. El misterio del `None` en las Bases de Datos
¿Puede una base de datos venir con `None`? Sí y no.
* En la Base de Datos (SQL): Se llama `NULL`. Es un estado que indica que el valor es desconocido o no aplicable.
* Al importar a Python: El conector de la base de datos traduce ese `NULL` de SQL al `None` de Python.
* ¿es "grave"? `None` es un objeto de tipo `NoneType`.
No puedes sumar `5 + None` = ❌ (daría error) rompe la operación: `10 + None = Error`
Pero pandas lo convierte a NaN para evitar errores.
Pues sí puedes sumar `5 + NaN` (el resultado es `NaN`). Por eso Pandas prefiere convertir los `None` a `NaN`: para que el código no "explote" al hacer cálculos.


#### 3. ¿Por qué aparecen valores nulos en un dataset?
Los valores faltantes existen porque los datos del mundo real nunca están completos.
Causas comunes:
campo olvidado de llenar en un formulario
dato ilegible en un documento
usuario no quiso compartir edad
información protegida
Dato no aplicable como “segundo apellido” vacío
Error técnico como: sensor falló
fallo en transmisión de datos
scraping incompleto
Integración de múltiples fuentes
como: bases de datos con estructuras diferentes
campos inexistentes en una fuente
Los nulos no son errores necesariamente: a veces representan información desconocida.

JSON { "edad": null } → se convierte a: None por Python, si la columna es numérica.
Base de datos: NULL → Python recibe: None → pandas lo convierte a: NaN

df.describe()
✔ ignora automáticamente valores NaN
✔ calcula estadísticas con los valores válidos
[10, 20, NaN, 30] →  promedio = 20

NumPy puro falla ante el valor nan: 
5 + np.nan =  nan #Se propaga como “valor desconocido”.
NumPy puro falla por ejemplo a calcular el promedio: 
np.mean([10, 20, np.nan])
resultado: nan
Pero pandas:
pd.Series([10,20,np.nan]).mean()
resultado: 15
Pandas ignora NaN automáticamente.
pandas ignora NaN en Sumas:
10 + 20 + NaN = 30
NaN no cuenta como valor para CONTEOS:
count = 2

`""` (Vacío)(tipo: string) | Es una cadena de texto de longitud cero.
Pandas

Imagina que estás organizando una carrera de ciclismo:
0 → llegó en 0 segundos
NaN → corrió pero no sabemos el tiempo
None → nunca participó
"" → alguien escribió el nombre pero dejó el tiempo vacío


df.dropna()        # eliminar
df.fillna(0)       # reemplazar
df.fillna(df.mean())  # estimar