In [82]:
import pandas as pd
import numpy as np
import io
# CONFIGURACION GENERAL_ Solo para visualización; Esto afecta a todos los print de numpy que hagas después
np.set_printoptions(precision=3, suppress=True)#precision=3→3decimales;suppress=True→no usar notación científica

# 1. Tu variable con los datos  con valores null, NaN, None, etc.
data_string = """ID,Producto,Categoría,Ventas,Precio Unitario,Total Ventas,Región
1,Laptop,Electrónica,15,1200.00,18000.00,Norte
2,Monitor,Computación,8,500.00,4000.00,Sur
3,Teclado,Accesorios,25,50.00,1250.00,Norte
4,Laptop,Electrónica,10,1100.00,11000.00,Este
5,Tablet,Computación,20,700.00,14000.00,Oeste
6,Impresora,Oficina,5,400.00,2000.00,Norte
7,Escáner,Oficina,5,210.00,1050.00,Oeste
8,Mouse,Accesorios,40,20.00,800.00,Este
9,Monitor,Computación,12,450.00,5400.00,Oeste
10,Tablet,Computación,18,750.00,13500.00,Norte
11,Teclado,Accesorios,22,55.00,1210.00,Sur
12,Impresora,Oficina,7,420.00,2940.00,Este
13, Auriculares ,,10,80.00,800.00,Oeste
14,Mouse,Accesorios,35,25.00,875.00,Norte
15,Laptop,Electrónica,18,1150.00,20700.00,Sur
16,Tablet,Computación,15,680.00,10200.00,Este
17,Monitor,Computación,10,480.00,4800.00,Oeste
18,Teclado,Accesorios,30,60.00,1800.00,Norte
19,Impresora,Oficina,12,450.00,5400.00,Sur
21,Webcam,Accesorios,15,85.00,None,Norte
22,Micrófono,Audio,8,,3200.00,Norte
23,Escáner,,5,210.00,1050.00,Oeste
24,Silla Gamer,Oficina,12,350.00,,Sur
25,Disco Duro,Computación,NaN,120.00,240.00,Este
26,Cargador,Accesorios,20,25.00,500.00,null
27,Monitor,Computación,null,450.00,null,Norte
28,Teclado,Accesorios,25,55.00,1375.00,null
29,Micrófono,Audio,10,null,4000.00,Sur
30, Cable USB,Accesorios,10,80.00,800.00,Oeste
30, Cable USB,Accesorios,null,null,800.00,Oeste
31, ssd externo,Computación,null,150.00,0,Norte
32,  ,Computación,null,150.00,0,Sur
"""
     
'''
NOTA
None (Fila 21): Es el nulo nativo de Python. Pandas suele convertirlo automáticamente a NaN en columnas numéricas.
Espacio vacío ,, (Fila 22 y 23): Es lo más común en archivos CSV. Pandas lo detectará inmediatamente como un valor faltante.
NaN (Fila 25): Significa Not a Number. Es el estándar de NumPy y Pandas para representar datos nulos en columnas de números.
null (Fila 26): Es común si los datos vienen de una base de datos SQL o de un archivo JSON.
'''

df = pd.read_csv(io.StringIO(data_string))

# data = {
#     "ID": [1,2,3,4,5,6,7,8,9,10],
#     "Producto": ["Laptop", "Monitor", "Teclado", "Laptop", "Tablet", "Impresora", "Smartphone", "Mouse", "Monitor", "Tablet"],
#     "Categoría": ["Electrónica", "Computación", "Accesorios", "Electrónica", "Computación", "Oficina", "Electrónica", "Accesorios", "Computación", "Computación"],
#     "Ventas": [15, 8, 25, 10, 20, 5, 30, 40, 12, 18],
#     "Precio Unitario": [1200, 500, 50, 1100, 700, 400, 800, 20, 450, 750],
#     "Total Ventas": [18000, 4000, 1250, 11000, 14000, 2000, 24000, 800, 5400, 13500],
#     "Región": ["Norte", "Sur", "Norte", "Este", "Oeste", "Norte", "Sur", "Este", "Oeste", "Norte"]
# }

In [42]:
print("###########"*10)
print("\n-------- CABECERA  ------- \n")
print(df.head())
print("-----"*20)

##############################################################################################################

-------- CABECERA  -------

   ID Producto    Categoría  Ventas  Precio Unitario  Total Ventas Región
0   1   Laptop  Electrónica    15.0           1200.0       18000.0  Norte
1   2  Monitor  Computación     8.0            500.0        4000.0    Sur
2   3  Teclado   Accesorios    25.0             50.0        1250.0  Norte
3   4   Laptop  Electrónica    10.0           1100.0       11000.0   Este
4   5   Tablet  Computación    20.0            700.0       14000.0  Oeste
----------------------------------------------------------------------------------------------------

In [43]:
print("###########"*10)
print("\n-------- FOOTER (ultimos 6 registros)  ------- \n")
print(df.tail(7))
print("____"*20)

# Pandas maneja los None como NaN (Not a Number) automáticamente
# En columnas numéricas o de texto, None se convierte en NaN
# Pandas manejo los espacios vacíos (,,) como NaN automáticamente
# Pandas maneja los null como NaN automáticamente.
# Pandas maneja los NaN como valores faltantes en columnas numéricas

##############################################################################################################

-------- FOOTER (ultimos 6 registros)  -------

    ID      Producto    Categoría  Ventas  Precio Unitario  Total Ventas  \
25  27       Monitor  Computación     NaN            450.0           NaN
26  28       Teclado   Accesorios    25.0             55.0        1375.0
27  29     Micrófono        Audio    10.0              NaN        4000.0
28  30     Cable USB   Accesorios    10.0             80.0         800.0
29  30     Cable USB   Accesorios     NaN              NaN         800.0
30  31   ssd externo  Computación     NaN            150.0           0.0
31  32                Computación     NaN            150.0           0.0

   Región
25  Norte
26    NaN
27    Sur
28  Oeste
29  Oeste
30  Norte
31    Sur
________________________________________________________________________________

In [44]:
#Dimensión del dataset
# fila, colum = df.shape
filas = df.shape[0]  # Número de filas
columnas = df.shape[1]  # Número de columnas
print("###########"*10)
print("\n-------- Dimensión del dataset -------  \n")
print(f"El dataset tiene {filas} filas y {columnas} columnas.")
print("-----"*20)

##############################################################################################################

-------- Dimensión del dataset -------

El dataset tiene 32 filas y 7 columnas.
----------------------------------------------------------------------------------------------------

In [45]:
# Columnas del dataset
print("###########"*10)
print("\n--------  Columnas del dataset -------  \n")
columnas = df.columns
print("Las columnas del dataset son:")
print(columnas)

print("-----"*20)

##############################################################################################################

--------  Columnas del dataset -------

Las columnas del dataset son:
Index(['ID', 'Producto', 'Categoría', 'Ventas', 'Precio Unitario',
       'Total Ventas', 'Región'],
      dtype='str')
----------------------------------------------------------------------------------------------------

In [46]:
# Tipos de datos de cada columna
print("###########"*10)
print("------ Tipos de datos de cada columna: ------- \n")
print(df.dtypes)
print("-----"*20)

##############################################################################################################
------ Tipos de datos de cada columna: -------

ID                   int64
Producto               str
Categoría              str
Ventas             float64
Precio Unitario    float64
Total Ventas       float64
Región                 str
dtype: object
----------------------------------------------------------------------------------------------------

In [47]:
# Acceder a una columna específica (por ejemplo, 'Total Ventas')
daily_sales = df['Total Ventas']
print("Serie 'Total Ventas':")
print(daily_sales)
print(type(daily_sales))

print("------ Tercer valor de la columna 'Total Ventas': -------")
print(daily_sales[2])

Serie 'Total Ventas':
0     18000.0
1      4000.0
2      1250.0
3     11000.0
4     14000.0
5      2000.0
6      1050.0
7       800.0
8      5400.0
9     13500.0
10     1210.0
11     2940.0
12      800.0
13      875.0
14    20700.0
15    10200.0
16     4800.0
17     1800.0
18     5400.0
19        NaN
20     3200.0
21     1050.0
22        NaN
23      240.0
24      500.0
25        NaN
26     1375.0
27     4000.0
28      800.0
29      800.0
30        0.0
31        0.0
Name: Total Ventas, dtype: float64
<class 'pandas.Series'>
------ Tercer valor de la columna 'Total Ventas': -------
1250.0

In [48]:
resumen_limpio  = df.describe().T[['count', 'mean', 'min', '50%', 'max']].rename(columns={
    'count': 'Cantidad',
    'mean': 'Promedio',
    'min': 'Mínimo',
    '50%': 'Mediana',
    'max': 'Máximo'
})
print("###########"*10)
print("\n-------- ESTADISTICAS -------\n")
print(resumen_limpio)
print("-----"*20)

##############################################################################################################

-------- ESTADISTICAS -------

                 Cantidad     Promedio  Mínimo  Mediana   Máximo
ID                   32.0    16.812500     1.0     16.5     32.0
Ventas               27.0    15.629630     5.0     12.0     40.0
Precio Unitario      29.0   360.517241    20.0    210.0   1200.0
Total Ventas         29.0  4541.034483     0.0   1800.0  20700.0
----------------------------------------------------------------------------------------------------

In [49]:
# Contar valores únicos en cada columna.
print("###########"*10)
print("------- Número de valores únicos por columna:---------")
print("Número de valores únicos por columna:")
valores_unicos_antes_de_limpieza = df.nunique().sort_values()
display(valores_unicos_antes_de_limpieza)
print("-----"*20)

##############################################################################################################
------- Número de valores únicos por columna:---------
Número de valores únicos por columna:

Región              4
Categoría           5
Ventas             13
Producto           16
Total Ventas       22
Precio Unitario    22
ID                 31
dtype: int64

----------------------------------------------------------------------------------------------------

In [50]:
num_null = df.isnull().sum()
print("###########"*10)
print("--- Número de valores nulos por columna:---")
display(num_null)
print("-----"*20)

# Realmente no son nulos, sino que son valores faltantes representados por None, NaN, null o espacios vacíos. Pandas los interpreta como NaN automáticamente.

##############################################################################################################
--- Número de valores nulos por columna:---

ID                 0
Producto           0
Categoría          2
Ventas             5
Precio Unitario    3
Total Ventas       3
Región             2
dtype: int64

----------------------------------------------------------------------------------------------------

In [51]:
# Filas que tienen valores nulos
nulos = df.isnull().sum()
print("Valores nulos por columna:")
print(nulos[nulos > 0])

Valores nulos por columna:
Categoría          2
Ventas             5
Precio Unitario    3
Total Ventas       3
Región             2
dtype: int64

In [52]:
# Porcentaje de valores nulos por columna
#df.isna().mean()*100).round(2))
# print(f"{(df.isna().mean()*100).round(2)}")
reporte_nulos = (df.isna().mean() * 100).round(2).map("{:.2f} %".format)
print("Porcentaje de valores nulos por columna:")
print(reporte_nulos)

Porcentaje de valores nulos por columna:
ID                  0.00 %
Producto            0.00 %
Categoría           6.25 %
Ventas             15.62 %
Precio Unitario     9.38 %
Total Ventas        9.38 %
Región              6.25 %
dtype: str

In [53]:
# Filas que contienen al menos un valor nulo
row_null = df[df.isnull().any(axis=1)]
display(row_null)

,ID,Producto,Categoría,Ventas,Precio Unitario,Total Ventas,Región
12,13,Auriculares,NaN,10.0,80.0,800.0,Oeste
19,21,Webcam,Accesorios,15.0,85.0,NaN,Norte
20,22,Micrófono,Audio,8.0,NaN,3200.0,Norte
21,23,Escáner,NaN,5.0,210.0,1050.0,Oeste
22,24,Silla Gamer,Oficina,12.0,350.0,NaN,Sur
23,25,Disco Duro,Computación,NaN,120.0,240.0,Este
24,26,Cargador,Accesorios,20.0,25.0,500.0,NaN
25,27,Monitor,Computación,NaN,450.0,NaN,Norte
26,28,Teclado,Accesorios,25.0,55.0,1375.0,NaN
27,29,Micrófono,Audio,10.0,NaN,4000.0,Sur
29,30,Cable USB,Accesorios,NaN,NaN,800.0,Oeste
30,31,ssd externo,Computación,NaN,150.0,0.0,Norte
31,32,,Computación,NaN,150.0,0.0,Sur

**Manejo de Regiones**

In [54]:
# Eliminar espacios invisibles (normalizacion de formato)


df["Categoría"] = df["Categoría"].str.strip()
df["Región"] = df["Región"].str.strip()
df["Producto"] = df["Producto"].str.strip()
# df["Producto"].replace("", np.nan, inplace=True)
# df["Producto"] = (
#     df["Producto"]
#     .str.strip()
#     .replace(r"^\s*$", np.nan, regex=True)
# )
df.loc[
    ~df["Producto"].str.contains(r"[a-zA-Z0-9]", na=False),
        #selecciona los que NO tienen letras ni números; como filas con espacios, símbolos, texto vacío
    "Producto"
] = np.nan
    # Esto es una asignación. cambia los valores seleccionados y los reemplaza por NaN

In [55]:
# Filas donde la columna 'Región' tiene valores nulos
print(df[df["Región"].isna()])

    ID  Producto   Categoría  Ventas  Precio Unitario  Total Ventas Región
24  26  Cargador  Accesorios    20.0             25.0         500.0    NaN
26  28   Teclado  Accesorios    25.0             55.0        1375.0    NaN

In [56]:
# ---------- 5️⃣ TRATAR REGIÓN ----------
# opción A: marcar como desconocida
# df["Región"].fillna("Sin región", inplace=True)

# opción B (alternativa): eliminar filas sin región
df = df.dropna(subset=["Región"])

**Limpieza de Categoria**

In [57]:
# ---------- 0️⃣ PREPARACIÓN: IDENTIFICAR Y GUARDAR ÍNDICES ----------

# Buscamos las filas donde 'Categoría' es nula
indices_nulos_cat = df[df["Categoría"].isna()].index
print(f"Se encontraron {len(indices_nulos_cat)} filas con Categoría nula.")
print("\n--- FILAS ANTES DE LA LIMPIEZA (Solo las afectadas) ---")
print(df.loc[indices_nulos_cat])


# ---------- 1️⃣ TU CÓDIGO DE LIMPIEZA ----------

# Aplicamos la lógica de completar por producto o poner 'Desconocido'
df["Categoría"] = df.groupby("Producto")["Categoría"]\
                    .transform(lambda x: x.fillna(x.mode()[0] if not x.mode().empty else "Desconocido"))

# Si aún quedan vacíos (casos donde no hubo coincidencia)
# df["Categoría"].fillna("Desconocido", inplace=True) # Descontinuado 
df["Categoría"] = df["Categoría"].fillna("Desconocido")
# Red de seguridad para cualquier caso que se nos haya pasado:
# ✔ productos únicos sin categoría
# ✔ datos corruptos
# ✔ inconsistencias

"""
df.groupby("Producto") -> Agrupa filas que tienen el mismo producto.
Grupo: Mouse:
Accesorios
NaN
Accesorios
df.groupby("Producto")["Categoría"] -> Ahora cada grupo solo contiene esa columna.
transform(): ->
✔ aplica una función a cada grupo
✔ devuelve el resultado con el mismo tamaño del DataFrame
✔ permite reasignarlo a la columna original
Sin transform(), perderías la forma original (n°filas, etc).
ambda x: ...  ->  x representa la columna Categoría dentro de cada grupo.
x.fillna(...) -> Rellena los valores faltantes dentro del grupo.
x.mode()[0] -> valor usamos para rellenar
mode() -> Devuelve una serie, tomamos el valor más frecuente.
if not x.mode().empty  -> Rellenar
Si está vacío:  ->   else "Desconocido"
"""

# ---------- 2️⃣ VERIFICACIÓN: COMPARAR EL DESPUÉS ----------

print("\n--- FILAS DESPUÉS DE LA LIMPIEZA (Mismos índices) ---")
# Usamos .loc con los índices que guardamos al principio
print(df.loc[indices_nulos_cat])
# df[df["Categoría"] == "Desconocido"]

Se encontraron 2 filas con Categoría nula.

--- FILAS ANTES DE LA LIMPIEZA (Solo las afectadas) ---
    ID     Producto Categoría  Ventas  Precio Unitario  Total Ventas Región
12  13  Auriculares       NaN    10.0             80.0         800.0  Oeste
21  23      Escáner       NaN     5.0            210.0        1050.0  Oeste

--- FILAS DESPUÉS DE LA LIMPIEZA (Mismos índices) ---
    ID     Producto    Categoría  Ventas  Precio Unitario  Total Ventas Región
12  13  Auriculares  Desconocido    10.0             80.0         800.0  Oeste
21  23      Escáner      Oficina     5.0            210.0        1050.0  Oeste

In [58]:
# Vista mas legible del código para completar la categoría faltante con la moda por producto, y si no hay moda, asignar "Desconocido".

# def completar_categoria(grupo):
#     moda = grupo.mode()

#     if not moda.empty:
#         return grupo.fillna(moda[0])
#     else:
#         return grupo.fillna("Desconocido")

# df["Categoría"] = df.groupby("Producto")["Categoría"].transform(completar_categoria)
# df["Categoría"] = df["Categoría"].fillna("Desconocido")

**LIMPIAR PRECIO UNITARIO**

In [ ]:
# ---------- 0️⃣ PREPARACIÓN: IDENTIFICAR Y GUARDAR ÍNDICES ----------

# Buscamos las filas donde 'Precio Unitario' es nula
indices_nulos_cat = df[df["Precio Unitario"].isna()].index
print(f"Se encontraron {len(indices_nulos_cat)} filas con Precio Unitario nula.")
print("\n--- FILAS ANTES DE LA LIMPIEZA (Solo las afectadas) ---")
print(df.loc[indices_nulos_cat])


# ---------- 1️⃣ LIMPIAR PRECIO UNITARIO ----------


# 1️⃣ Calcular precio unitario si faltante pero existen Total_Ventas y Ventas
# Precio Unitario = Total Ventas / Ventas
mask = df["Precio Unitario"].isna() & df["Total Ventas"].notna() & df["Ventas"].notna()
# mask es un filtro lógico que identifica filas donde:
# -falta el precio unitario
# -sí existe el total de ventas
# -sí existe la cantidad vendida
# print("Validando la lógica 'mask':")
# print(mask)
# 18    False
# 19    False
# 20     True
# 21    False
print("\n--- FILAS CON PRECIO UNITARIO NULO PERO TOTAL VENTAS Y VENTAS NO NULOS ---")
print(df.loc[mask])
# --- FILAS CON PRECIO UNITARIO NULO PERO TOTAL VENTAS Y VENTAS NO NULOS ---
#     ID   Producto Categoría  Ventas  Precio Unitario  Total Ventas Región
# 20  22  Micrófono     Audio     8.0              NaN        3200.0  Norte
# 27  29  Impresora   Oficina    10.0              NaN        4000.0    Sur
# ignora:
# --  30  Cable USB  Accesorios     NaN              NaN         800.0  Oeste
df.loc[mask, "Precio Unitario"] = df.loc[mask, "Total Ventas"] / df.loc[mask, "Ventas"]

# 2️⃣ Usar promedio del mismo producto
df["Precio Unitario"] = df.groupby("Producto")["Precio Unitario"]\
    .transform(lambda x: x.fillna(x.mean())) # Uso de la Media para rellenar el precio unitario faltante dentro de cada grupo de producto.

# 3️⃣ NO rellenar con promedio global
# df["Precio Unitario"].fillna(df["Precio Unitario"].mean(), inplace=True)
# df["Precio Unitario"] = df["Precio Unitario"].fillna(df["Precio Unitario"].mean())
# dejamos NaN si no se pudo inferir



# ---------- 2️⃣ VERIFICACIÓN: COMPARAR EL DESPUÉS ----------
print("\n--- FILAS DESPUÉS DE LA LIMPIEZA (Mismos índices) ---")
# Usamos .loc con los índices que guardamos al principio
print(df.loc[indices_nulos_cat])

Se encontraron 3 filas con Precio Unitario nula.

--- FILAS ANTES DE LA LIMPIEZA (Solo las afectadas) ---
    ID   Producto   Categoría  Ventas  Precio Unitario  Total Ventas Región
20  22  Micrófono       Audio     8.0              NaN        3200.0  Norte
27  29  Micrófono       Audio    10.0              NaN        4000.0    Sur
29  30  Cable USB  Accesorios     NaN              NaN         800.0  Oeste

--- FILAS CON PRECIO UNITARIO NULO PERO TOTAL VENTAS Y VENTAS NO NULOS ---
    ID   Producto Categoría  Ventas  Precio Unitario  Total Ventas Región
20  22  Micrófono     Audio     8.0              NaN        3200.0  Norte
27  29  Micrófono     Audio    10.0              NaN        4000.0    Sur

--- FILAS DESPUÉS DE LA LIMPIEZA (Mismos índices) ---
    ID   Producto   Categoría  Ventas  Precio Unitario  Total Ventas Región
20  22  Micrófono       Audio     8.0            400.0        3200.0  Norte
27  29  Micrófono       Audio    10.0            400.0        4000.0    Sur
29  30  Cable USB  Accesorios     NaN             80.0         800.0  Oeste

In [60]:
row_null = df[df.isnull().any(axis=1)]
display(row_null)

    ID     Producto    Categoría  Ventas  Precio Unitario  Total Ventas Región
19  21       Webcam   Accesorios    15.0             85.0           NaN  Norte
22  24  Silla Gamer      Oficina    12.0            350.0           NaN    Sur
23  25   Disco Duro  Computación     NaN            120.0         240.0   Este
25  27      Monitor  Computación     NaN            450.0           NaN  Norte
29  30    Cable USB   Accesorios     NaN             80.0         800.0  Oeste
30  31  ssd externo  Computación     NaN            150.0           0.0  Norte
31  32          NaN  Desconocido     NaN              NaN           0.0    Sur

**Limpieza de Ventas**

In [61]:
# ---------- 0️⃣ PREPARACIÓN: IDENTIFICAR Y GUARDAR ÍNDICES ----------

# Buscamos las filas donde 'Ventas' es nula
indices_nulos_cat = df[df["Ventas"].isna()].index

print(f"Se encontraron {len(indices_nulos_cat)} filas con Ventas nula.")
print("\n--- FILAS ANTES DE LA LIMPIEZA (Solo las afectadas) ---")
print(df.loc[indices_nulos_cat])

# ---------- 1️⃣ LIMPIAR VENTAS ----------

# Primero arreglamos los casos donde Total Ventas es 0
df.loc[df['Total Ventas'] == 0, 'Ventas'] = df['Ventas'].fillna(0)
#filtro de seguridad para paso posterior
# Ubica las filas donde el dinero recaudado es cero, y valida la columna de cantidad vendida,..
# Si en esa fila hay un NaN,  indicar un '0'

# # Luego calculamos: Ventas = Total / Precio (Solo donde Ventas sea NaN, no cero)
df['Ventas'] = df['Ventas'].fillna(df['Total Ventas'] / df['Precio Unitario'])

# # --- 2️⃣ REGLA DE GRUPO: Promedio por producto ---
# df["Ventas"] = df.groupby("Producto")["Ventas"]\
#                  .transform(lambda x: x.fillna(x.mean()))
# # --- 3️⃣ REGLA DE CIERRE: Último recurso ---
# df["Ventas"] = df["Ventas"].fillna(0)
'''
Antes se había propuesto rellenar con el promedio por producto para mantener la coherencia dentro de cada categoría de producto. Pero decidimos no hacerlo porque:
- Podría introducir sesgos si el producto tiene pocos registros o mucha variabilidad.
Se permite dejar el NaN en este caso, ya que no se puede inferir un valor razonable sin más información. Es mejor tener un NaN que un valor incorrecto.
'''

###### NO USADO 
# # rellenar con promedio del producto
# df["Ventas"] = df.groupby("Producto")["Ventas"]\
#                  .transform(lambda x: x.fillna(x.mean()))
# # si aún queda NaN
# # df["Ventas"].fillna(0, inplace=True)
# df ["Ventas"] = df["Ventas"].fillna(0)  


# ---------- 2️⃣ VERIFICACIÓN: COMPARAR EL DESPUÉS ----------

print("\n--- FILAS DESPUÉS DE LA LIMPIEZA (Mismos índices) ---")
# Usamos .loc con los índices que guardamos al principio
print(df.loc[indices_nulos_cat])

Se encontraron 5 filas con Ventas nula.

--- FILAS ANTES DE LA LIMPIEZA (Solo las afectadas) ---
    ID     Producto    Categoría  Ventas  Precio Unitario  Total Ventas Región
23  25   Disco Duro  Computación     NaN            120.0         240.0   Este
25  27      Monitor  Computación     NaN            450.0           NaN  Norte
29  30    Cable USB   Accesorios     NaN             80.0         800.0  Oeste
30  31  ssd externo  Computación     NaN            150.0           0.0  Norte
31  32          NaN  Desconocido     NaN              NaN           0.0    Sur

--- FILAS DESPUÉS DE LA LIMPIEZA (Mismos índices) ---
    ID     Producto    Categoría  Ventas  Precio Unitario  Total Ventas Región
23  25   Disco Duro  Computación     2.0            120.0         240.0   Este
25  27      Monitor  Computación     NaN            450.0           NaN  Norte
29  30    Cable USB   Accesorios    10.0             80.0         800.0  Oeste
30  31  ssd externo  Computación     0.0            150.0           0.0  Norte
31  32          NaN  Desconocido     0.0              NaN           0.0    Sur

**Limpieza de Precio Total Ventas**

In [62]:
# ---------- 0️⃣ PREPARACIÓN: IDENTIFICAR Y GUARDAR ÍNDICES ----------

# Buscamos las filas donde 'Total Ventas' es nula
indices_nulos_cat = df[df["Total Ventas"].isna()].index

print(f"Se encontraron {len(indices_nulos_cat)} filas con Total Ventas nula.")
print("\n--- FILAS ANTES DE LA LIMPIEZA (Solo las afectadas) ---")
print(df.loc[indices_nulos_cat])

# ---------- 1️⃣ LIMPIAR VENTAS ----------

df["Total Ventas"] = df["Total Ventas"].fillna(
        df["Ventas"] * df["Precio Unitario"]
    )

# ---------- 2️⃣ VERIFICACIÓN: COMPARAR EL DESPUÉS ----------

print("\n--- FILAS DESPUÉS DE LA LIMPIEZA (Mismos índices) ---")
# Usamos .loc con los índices que guardamos al principio
print(df.loc[indices_nulos_cat])

Se encontraron 3 filas con Total Ventas nula.

--- FILAS ANTES DE LA LIMPIEZA (Solo las afectadas) ---
    ID     Producto    Categoría  Ventas  Precio Unitario  Total Ventas Región
19  21       Webcam   Accesorios    15.0             85.0           NaN  Norte
22  24  Silla Gamer      Oficina    12.0            350.0           NaN    Sur
25  27      Monitor  Computación     NaN            450.0           NaN  Norte

--- FILAS DESPUÉS DE LA LIMPIEZA (Mismos índices) ---
    ID     Producto    Categoría  Ventas  Precio Unitario  Total Ventas Región
19  21       Webcam   Accesorios    15.0             85.0        1275.0  Norte
22  24  Silla Gamer      Oficina    12.0            350.0        4200.0    Sur
25  27      Monitor  Computación     NaN            450.0           NaN  Norte

**Limpieza de valores nulos en la columna "Producto"**

In [63]:
# ---------- 0️⃣ PREPARACIÓN: IDENTIFICAR Y GUARDAR ÍNDICES ----------

# Buscamos las filas donde 'Producto' es nula
indices_nulos_cat = df[df["Producto"].isna()].index
print(f"Se encontraron {len(indices_nulos_cat)} filas con Producto nula.")
print("\n--- FILAS ANTES DE LA LIMPIEZA (Solo las afectadas) ---")
print(df.loc[indices_nulos_cat])

# ---------- 1️⃣ TU CÓDIGO DE LIMPIEZA ----------

# df["Producto"].fillna("Desconocido", inplace=True) # Descontinuado 
df["Producto"] = df["Producto"].fillna("Desconocido")

# ---------- 2️⃣ VERIFICACIÓN: COMPARAR EL DESPUÉS ----------
print("\n--- FILAS DESPUÉS DE LA LIMPIEZA (Mismos índices) ---")
# Usamos .loc con los índices que guardamos al principio
print(df.loc[indices_nulos_cat])

Se encontraron 1 filas con Producto nula.

--- FILAS ANTES DE LA LIMPIEZA (Solo las afectadas) ---
    ID Producto    Categoría  Ventas  Precio Unitario  Total Ventas Región
31  32      NaN  Desconocido     0.0              NaN           0.0    Sur

--- FILAS DESPUÉS DE LA LIMPIEZA (Mismos índices) ---
    ID     Producto    Categoría  Ventas  Precio Unitario  Total Ventas Región
31  32  Desconocido  Desconocido     0.0              NaN           0.0    Sur

**Reglas de eliminación de filas**

In [64]:
# Regla, si no posee 'Total Venta's y 'Ventas' se elimina regitro
df = df.dropna(subset=["Total Ventas", "Ventas"])

# Borra filas que tengan menos de 3 columnas con datos válidos
# df.dropna(thresh=3, inplace=True)

**Validacion Final**

In [65]:
row_null = df[df.isnull().any(axis=1)]
display(row_null)
print("____"*10)
print("\nNulos restantes:")
print(df.isnull().sum())

    ID     Producto    Categoría  Ventas  Precio Unitario  Total Ventas Región
31  32  Desconocido  Desconocido     0.0              NaN           0.0    Sur

________________________________________

Nulos restantes:
ID                 0
Producto           0
Categoría          0
Ventas             0
Precio Unitario    1
Total Ventas       0
Región             0
dtype: int64

**Eliminación de filas MANUAL**

In [66]:
# Se eliminara la fila de ID 32 porque no tiene información relevante,
# ni siquiera el producto. No se puede inferir nada útil de esa fila, y podría distorsionar análisis futuros.
# Ademas no porsee 'Ventas' ni 'Total Ventas', lo que no aporta al análisis. 

# Eliminamos la fila por su etiqueta de índice

# indice del registro a eliminar
indice_a_eliminar = df[df["ID"] == 32].index
df = df.drop(indice_a_eliminar) #.drop() elimina la fila por su índice!

# "Mantén todas las filas donde el ID no sea 32"
# df = df[df["ID"] != 32] # Elimina la fila donde la columna 'ID' es igual a 32

**FIANLIZADA LA LIMPIEZA DE DATOS, AHORA PASAMOS A LA EXPLORACIÓN DE LOS DATOS.**

In [67]:
print("#########"*10)
print("------- Número de valores únicos por columna Antes y Despues:---------")
valores_unicos_despues_de_limpieza = df.nunique().sort_values()

comparacion = pd.concat(
    [valores_unicos_antes_de_limpieza, valores_unicos_despues_de_limpieza],
    axis=1
)

comparacion.columns = ["Antes", "Después"]
comparacion["Diferencia"] = comparacion["Después"] - comparacion["Antes"]
# comparacion[comparacion["Diferencia"] != 0]


display(comparacion)

print("_____"*18)

##########################################################################################
------- Número de valores únicos por columna Antes y Despues:---------

                 Antes  Después  Diferencia
Región               4        4           0
Categoría            5        6           1
Ventas              13       15           2
Producto            16       14          -2
Total Ventas        22       22           0
Precio Unitario     22       22           0
ID                  31       27          -4

__________________________________________________________________________________________

In [68]:
# Datos estadisticos por Separados por Columna 
# .median()
# .mode()
# .mean()
# .sum()
# .count()
# .max()
# .min()
# .quantile()
# .var()
# .std()
# .value_counts() # Cuenta la frecuencia de cada valor único en una columna. Es útil para columnas categóricas o discretas, ya que muestra cuántas veces aparece cada valor en la columna.
# .unique() # Devuelve un array de los valores únicos presentes en una columna. Es útil para entender la diversidad de valores en una columna, especialmente en columnas categóricas.
# .nunique() # Devuelve el número de valores únicos en una columna. Es útil para obtener una rápida visión general de la cantidad de categorías o valores distintos en una columna.
# .describe() # VER ARRIBA

# Calculo de mediana de la columna 'Ventas'
mediana_ventas = df['Ventas'].median()
print("\n-------- Mediana de la columna 'Ventas': ------- \n")
print(f"La mediana de la columna 'Ventas' es: {mediana_ventas}")
print("______"*10)

# Calculo de moda de la columna 'Categoría'
moda_categoria = df['Categoría'].mode()[0]
print("\n-------- Moda de la columna 'Categoría': ------- \n")
print(f"La moda de la columna 'Categoría' es: {moda_categoria}")
# .mode()[1] es para obtener la segunda moda si existe
print("______"*10)

# Calculo de rango de la columna 'Ventas'
# Rango = Valor máximo - Valor mínimo 
# .range() no existe como método directo en pandas, pero se puede calcular restando el valor mínimo al valor máximo de una columna.
rango_ventas = df['Ventas'].max() - df['Ventas'].min()
print("\n-------- Rango de la columna 'Ventas': ------- \n")
print(f"El rango de la columna 'Ventas' es: {rango_ventas}")
print("______"*10)   

# Cuartiles de la columna 'Total Ventas'
cuartiles_total_ventas = df['Total Ventas'].quantile([0.25, 0.5, 0.75])
print("\n-------- Cuartiles de la columna 'Total Ventas': ------- \n")
print("Cuartiles de la columna 'Total Ventas':")
print(cuartiles_total_ventas)
print("______"*10)

# Calculo de media de la columna 'Ventas'
mean_ventas = df['Ventas'].mean()
print(f" --- La media de la columna 'Ventas' es: {mean_ventas:.2f}")
# Salida: La media de la columna 'Ventas' es: 18.30
print("______"*10)

# Calculo de suma de la columna 'Ventas'
suma_ventas = df['Ventas'].sum()
print(f" --- La suma de la columna 'Ventas' es: {suma_ventas}")
# Salida: La suma de la columna 'Ventas' es: 183
print("______"*10)

# Calculo de conteo de la columna 'Ventas'
conteo_ventas = df['Ventas'].count()
print(f" --- El conteo de la columna 'Ventas' es: {conteo_ventas}")
# Salida: El conteo de la columna 'Ventas' es: 10

-------- Mediana de la columna 'Ventas': -------

La mediana de la columna 'Ventas' es: 11.0
____________________________________________________________

-------- Moda de la columna 'Categoría': -------

La moda de la columna 'Categoría' es: Accesorios
____________________________________________________________

-------- Rango de la columna 'Ventas': -------

El rango de la columna 'Ventas' es: 40.0
____________________________________________________________

-------- Cuartiles de la columna 'Total Ventas': -------

Cuartiles de la columna 'Total Ventas':
0.25    1006.25
0.50    2470.00
0.75    5400.00
Name: Total Ventas, dtype: float64
____________________________________________________________
 --- La media de la columna 'Ventas' es: 13.89
____________________________________________________________
 --- La suma de la columna 'Ventas' es: 389.0
____________________________________________________________
 --- El conteo de la columna 'Ventas' es: 28

In [69]:
print("\n ################################################## ")
# Calculo de varianza de la columna 'Precio Unitario'
varianza_precio = df['Precio Unitario'].var()
print("\n-------- Varianza de la columna 'Precio Unitario': ------- \n")
print(f"La varianza de la columna 'Precio Unitario' es: {varianza_precio:.2f}")
print("______"*10)
# Calculo de desviación estándar de la columna 'Total Ventas'
desviacion_total_ventas = df['Total Ventas'].std()
print("\n-------- Desviación estándar de la columna 'Total Ventas': ------- \n")
print(f"La desviación estándar de la columna 'Total Ventas' es: {desviacion_total_ventas:.2f}")
print("______"*10)   
# Calculo de coeficiente de variación de la columna 'Precio Unitario'
coeficiente_variacion_precio = (df['Precio Unitario'].std() / df['Precio Unitario'].mean()) * 100 
print("\n-------- Coeficiente de variación de la columna 'Precio Unitario': ------- \n")
print(f"El coeficiente de variación de la columna 'Precio Unitario' es: {coeficiente_variacion_precio:.2f}%")   
print("______"*10)

 ##################################################

-------- Varianza de la columna 'Precio Unitario': -------

La varianza de la columna 'Precio Unitario' es: 120695.07
____________________________________________________________

-------- Desviación estándar de la columna 'Total Ventas': -------

La desviación estándar de la columna 'Total Ventas' es: 5674.67
____________________________________________________________

-------- Coeficiente de variación de la columna 'Precio Unitario': -------

El coeficiente de variación de la columna 'Precio Unitario' es: 91.30%
____________________________________________________________

In [70]:
# .value_counts() # Cuenta la frecuencia de cada valor único en una columna. Es útil para columnas categóricas o discretas, ya que muestra cuántas veces aparece cada valor en la columna.
# .unique() # Devuelve un array de los valores únicos presentes en una columna. Es útil para entender la diversidad de valores en una columna, especialmente en columnas categóricas.
# .nunique() # Devuelve el número de valores únicos en una columna. Es útil para obtener una rápida visión general de la cantidad de categorías o valores distintos en una columna.
# .describe() # VER ARRIBA

# Contar la frecuencia de cada valor único en la columna 'Categoría'
frecuencia_categoria = df['Categoría'].value_counts()
print("---- Frecuencia de cada valor único en la columna 'Categoría': ----- ")
print(frecuencia_categoria)
# Contar el número de valores únicos en la columna 'Región'
num_valores_unicos_region = df['Región'].nunique()
print("\n ---- Número de valores únicos en la columna 'Región': ----- ")
print(f"El número de valores únicos en la columna 'Región' es: {num_valores_unicos_region}")
valores_unicos_region = df['Región'].unique()
print("\n ---- Valores únicos presentes en la columna 'Región': ----- ")
print("Los valores únicos en la columna 'Región' son:") 
print(valores_unicos_region)
print("______"*10)
num_valores_unicos_regionvalores_unicos_producto = df['Producto'].nunique()
print("\n ---- Número de valores únicos en la columna 'Producto': ----- ")
print(f"El número de valores únicos en la columna 'Producto' es: {num_valores_unicos_regionvalores_unicos_producto}")
# Obtener los valores únicos presentes en la columna 'Producto'
valores_unicos_producto = df['Producto'].unique()
print("\n ---- Valores únicos presentes en la columna 'Producto': ----- ")
print("Los valores únicos en la columna 'Producto' son:")
print(valores_unicos_producto)

---- Frecuencia de cada valor único en la columna 'Categoría': -----
Categoría
Computación    8
Accesorios     8
Oficina        6
Electrónica    3
Audio          2
Desconocido    1
Name: count, dtype: int64

 ---- Número de valores únicos en la columna 'Región': -----
El número de valores únicos en la columna 'Región' es: 4

 ---- Valores únicos presentes en la columna 'Región': -----
Los valores únicos en la columna 'Región' son:
<StringArray>
['Norte', 'Sur', 'Este', 'Oeste']
Length: 4, dtype: str
____________________________________________________________

 ---- Número de valores únicos en la columna 'Producto': -----
El número de valores únicos en la columna 'Producto' es: 14

 ---- Valores únicos presentes en la columna 'Producto': -----
Los valores únicos en la columna 'Producto' son:
<StringArray>
[     'Laptop',     'Monitor',     'Teclado',      'Tablet',   'Impresora',
     'Escáner',       'Mouse', 'Auriculares',      'Webcam',   'Micrófono',
 'Silla Gamer',  'Disco Duro',   'Cable USB', 'ssd externo']
Length: 14, dtype: str

In [71]:
# Resumen estadístico de la columna 'Ventas'
resumen_ventas = df['Ventas'].describe()
print("\n ---- Resumen estadístico de la columna 'Ventas': ----- \n")
print(resumen_ventas)
print("______"*10)

 ---- Resumen estadístico de la columna 'Ventas': -----

count    28.000000
mean     13.892857
std       9.507655
min       0.000000
25%       8.000000
50%      11.000000
75%      18.000000
max      40.000000
Name: Ventas, dtype: float64
____________________________________________________________

In [72]:
#####otros métodos estadísticos útiles:
# .cov() # Covarianza entre dos columnas, pero no es un método directo para una sola columna. Se utiliza para calcular la covarianza entre dos columnas numéricas en un DataFrame.
            # Nota: La covarianza mide cómo dos variables cambian juntas. Si la covarianza es positiva, significa que ambas variables tienden a aumentar o disminuir juntas. Si es negativa, significa que una variable tiende a aumentar mientras la otra disminuye.
# .corr() # Correlación entre dos columnas, pero no es un método directo para una sola columna. Se utiliza para calcular la correlación entre dos columnas numéricas en un DataFrame.
            # Nota: La correlación mide la fuerza y la dirección de la relación lineal entre dos variables. El coeficiente de correlación varía entre -1 y 1, donde 1 indica una correlación positiva perfecta, -1 indica una correlación negativa perfecta y 0 indica que no hay correlación.
            # la correlación es una medida estandarizada de la covarianza, lo que significa que se encuentra en un rango específico (-1 a 1) y no depende de las unidades de medida de las variables.
# .skew() # Asimetría de la distribución de una columna numérica. Un valor de asimetría positivo indica que la distribución tiene una cola más larga hacia la derecha, mientras que un valor negativo indica una cola más larga hacia la izquierda. Un valor cercano a cero sugiere una distribución simétrica. Nota: normalmente, una distribución normal tiene una asimetría de aproximadamente 0.
# .kurt() # Curtosis de la distribución de una columna numérica. La curtosis mide la "agudeza" de la distribución. Un valor de curtosis positivo indica una distribución con colas más pesadas y un pico más alto que una distribución normal, mientras que un valor negativo indica una distribución con colas más ligeras y un pico más bajo. Un valor cercano a cero sugiere una distribución similar a la normal.

In [73]:
# .iloc() Se basa en la posición (número de índice).

# Seleccionar la primera fila del DataFrame utilizando .iloc()
first_row = df.iloc[0] 
print("-------- Primera fila del DataFrame utilizando .iloc(): ------- ")
print(first_row) # Agrupa los valores de la primera fila en una Serie de pandas, donde el índice de la Serie corresponde a los nombres de las columnas del DataFrame.
print("______"*10)

# Seleccionar el tercer valor de la columna 'Total Ventas' utilizando .iloc()
tercer_valor_total_ventas = df['Total Ventas'].iloc[2]
print("-------- Tercer valor de la columna 'Total Ventas' utilizando .iloc(): ------- ")
print(f"El tercer valor de la columna 'Total Ventas' es: {tercer_valor_total_ventas}")
print("______"*10)

# Seleccionar las primeras tres filas del DataFrame utilizando .iloc()
first_three_rows = df.iloc[:3]
print("-------- Primeras tres filas del DataFrame utilizando .iloc(): ------- ")
print(first_three_rows) # Devuelve un nuevo DataFrame que contiene las primeras tres filas del DataFrame original.
# Seleccionar las ultimas tres filas del DataFrame utilizando .iloc()
last_three_rows = df.iloc[-3:]
print("-------- Últimas tres filas del DataFrame utilizando .iloc(): ------- ")
print(last_three_rows)
print("______"*10)

# Seleccionar las filas del índice 2 al 4 del DataFrame utilizando .iloc()
first_five_row = df.iloc[2:5]
print("-------- Filas del índice 2 al 4 del DataFrame utilizando .iloc(): ------- ")
print(first_five_row)

-------- Primera fila del DataFrame utilizando .iloc(): -------
ID                           1
Producto                Laptop
Categoría          Electrónica
Ventas                    15.0
Precio Unitario         1200.0
Total Ventas           18000.0
Región                   Norte
Name: 0, dtype: object
____________________________________________________________
-------- Tercer valor de la columna 'Total Ventas' utilizando .iloc(): -------
El tercer valor de la columna 'Total Ventas' es: 1250.0
____________________________________________________________
-------- Primeras tres filas del DataFrame utilizando .iloc(): -------
   ID Producto    Categoría  Ventas  Precio Unitario  Total Ventas Región
0   1   Laptop  Electrónica    15.0           1200.0       18000.0  Norte
1   2  Monitor  Computación     8.0            500.0        4000.0    Sur
2   3  Teclado   Accesorios    25.0             50.0        1250.0  Norte
-------- Últimas tres filas del DataFrame utilizando .iloc(): -------
    ID     Producto    Categoría  Ventas  Precio Unitario  Total Ventas Región
28  30    Cable USB   Accesorios    10.0             80.0         800.0  Oeste
29  30    Cable USB   Accesorios    10.0             80.0         800.0  Oeste
30  31  ssd externo  Computación     0.0            150.0           0.0  Norte
____________________________________________________________
-------- Filas del índice 2 al 4 del DataFrame utilizando .iloc(): -------
   ID Producto    Categoría  Ventas  Precio Unitario  Total Ventas Región
2   3  Teclado   Accesorios    25.0             50.0        1250.0  Norte
3   4   Laptop  Electrónica    10.0           1100.0       11000.0   Este
4   5   Tablet  Computación    20.0            700.0       14000.0  Oeste

In [74]:
# Crear un subconjunto del DataFrame utilizando .iloc() para seleccionar las primeras tres filas y las primeras dos columnas.
subset = df.iloc[:3, :2]
print(subset)

print("______"*10)
# Crear un subconjunto del DataFrame para seleccionar las ultimas tres filas y la columna ID, Producto, Total Ventas y Región .
subset_last_three_rows = df.iloc[-3:, [0, 1, 2, 3]] # Selecciona las últimas tres filas y las columnas ID, Producto, Total Ventas y Región
print(subset_last_three_rows)
print("______"*10)

# retail_value = df.iloc[1, 3] # no da mayor info
retail_value = df.iloc[1, [1, 3]]
print("-------- Valor de la fila 1 y columna 'producto' y 'Ventas' utilizando .iloc(): ------- ")
print(retail_value)
# Acceso por posición (menos legible)
print(f"El valor del producto es '{retail_value.iloc[0]}' y las ventas son '{retail_value.iloc[1]}'")
# Acceso por nombre (más legible)
print(f"Producto: {retail_value['Producto']}, Ventas: {retail_value['Ventas']} unidades")
# Acceso por índice genera error porque retail_value es una Serie, no un DataFrame o una lista.
# ERROR -  NO VALIDO  # Series se parecen a las listas, tienen sus propias reglas de etiqueta.
# print(f"El valor del producto es '{retail_value[0]}' y las ventas son '{retail_value[1]}'") ### ERROR # Busca la etiqueta llamada 0

   ID Producto
0   1   Laptop
1   2  Monitor
2   3  Teclado
____________________________________________________________
    ID     Producto    Categoría  Ventas
28  30    Cable USB   Accesorios    10.0
29  30    Cable USB   Accesorios    10.0
30  31  ssd externo  Computación     0.0
____________________________________________________________
-------- Valor de la fila 1 y columna 'producto' y 'Ventas' utilizando .iloc(): -------
Producto    Monitor
Ventas          8.0
Name: 1, dtype: object
El valor del producto es 'Monitor' y las ventas son '8.0'
Producto: Monitor, Ventas: 8.0 unidades

In [ ]:
# crear una nueva columna 'IVA' y 'Precio con IVA' que sea el resultado de dividir
  
# df['IVA'] = df['Total Ventas'] * 0.19  # Suponiendo un IVA del 19%
df['IVA'] = df['Total Ventas'].apply(lambda x: x * 0.19 if pd.notnull(x) else np.nan)
df['Precio con IVA'] = df['Total Ventas'] + df['IVA']
df['HighValue_without_Iva'] = df['Total Ventas'] > 15000


def categorize_price(price):
  if price > 50:
    return 'High'
  elif price < 20:
    return 'Medium'
  else:
    return 'Low'

df['PriceCategory'] = df['UnitPrice'].apply(categorize_price)
print(df.head(10))



df.head()

,ID,Producto,Categoría,Ventas,Precio Unitario,Total Ventas,Región,IVA,Precio con IVA,HighValue_without_Iva
0,1,Laptop,Electrónica,15.0,1200.0,18000.0,Norte,3420.0,21420.0,True
1,2,Monitor,Computación,8.0,500.0,4000.0,Sur,760.0,4760.0,False
2,3,Teclado,Accesorios,25.0,50.0,1250.0,Norte,237.5,1487.5,False
3,4,Laptop,Electrónica,10.0,1100.0,11000.0,Este,2090.0,13090.0,False
4,5,Tablet,Computación,20.0,700.0,14000.0,Oeste,2660.0,16660.0,False

# PREGUNTAS TIPO RETO:::::

In [75]:
############## ¿Cuál es la cantidad total de productos vendidos? #######################
cantidad_total_productos = df['Ventas'].sum()
# print("La cantidad total de productos vendidos es:", cantidad_total_productos)
print(cantidad_total_productos)

389.0

In [76]:
# ¿Cuál es la categoría con mayor total de ventas acumuladas?
categoria_mayor_ventas = df.groupby('Categoría')['Total Ventas'].sum().idxmax()
# print("La categoría con mayor total de ventas acumuladas es:", categoria_mayor_ventas)
print(categoria_mayor_ventas)

Computación

In [77]:
# Mostrar solo los productos con un precio unitario mayor a 500 Y SIN DECIMALES
productos_precio_alto = df[df['Precio Unitario'] > 500].copy()
productos_precio_alto['Precio Unitario'] = productos_precio_alto['Precio Unitario'].astype(int)
productos_precio_alto['Total Ventas'] = productos_precio_alto['Total Ventas'].astype(int)
# print("Productos con un precio unitario mayor a 500:")
print(productos_precio_alto)

    ID Producto    Categoría  Ventas  Precio Unitario  Total Ventas Región
0    1   Laptop  Electrónica    15.0             1200         18000  Norte
3    4   Laptop  Electrónica    10.0             1100         11000   Este
4    5   Tablet  Computación    20.0              700         14000  Oeste
9   10   Tablet  Computación    18.0              750         13500  Norte
14  15   Laptop  Electrónica    18.0             1150         20700    Sur
15  16   Tablet  Computación    15.0              680         10200   Este

In [78]:
# Calcular el precio promedio de todos los productos.
precio_promedio = df['Precio Unitario'].mean()
# print("El precio promedio de todos los productos es:", precio_promedio
print(precio_promedio)

380.5357142857143

In [79]:

# Se crea una nueva columna llamada "Precio Actualizado" que aumente los precios en un 10%.
df['Precio Actualizado'] = df['Precio Unitario'] * 1.1
# print(df.head())

#Generar una tabla, Producto  Precio Unitario  Precio Actualizado:   #### MUY RECOMENDABLE EL USO DE .copy #### FORMA SEGURA ####
tabla_precio_actualizado = df[['Producto', 'Precio Unitario', 'Precio Actualizado']].copy()
# print(tabla_precio_actualizado)

# quitar decimales a: Precio Unitario
tabla_precio_actualizado['Precio Unitario'] = tabla_precio_actualizado['Precio Unitario'].astype(int)
print(tabla_precio_actualizado)

       Producto  Precio Unitario  Precio Actualizado
0        Laptop             1200              1320.0
1       Monitor              500               550.0
2       Teclado               50                55.0
3        Laptop             1100              1210.0
4        Tablet              700               770.0
5     Impresora              400               440.0
6       Escáner              210               231.0
7         Mouse               20                22.0
8       Monitor              450               495.0
9        Tablet              750               825.0
10      Teclado               55                60.5
11    Impresora              420               462.0
12  Auriculares               80                88.0
13        Mouse               25                27.5
14       Laptop             1150              1265.0
15       Tablet              680               748.0
16      Monitor              480               528.0
17      Teclado               60                66.0
18    Impresora              450               495.0
19       Webcam               85                93.5
20    Micrófono              400               440.0
21      Escáner              210               231.0
22  Silla Gamer              350               385.0
23   Disco Duro              120               132.0
27    Micrófono              400               440.0
28    Cable USB               80                88.0
29    Cable USB               80                88.0
30  ssd externo              150               165.0

### 📝 Nota de Estudio:

#### 1. ¿Por qué existe el `NaN` y qué tipo de dato es?

`NaN` (Not a Number) técnicamente es un número.
* ¿Por qué es un número? En computación, para que una columna de precios sea rápida de procesar, todos los elementos deben ser del mismo tipo (ej. `float64`). Si pusiéramos un string, la columna se volvería lenta.
`type(np.nan)`, es `<class 'float'>`. Es un "marcador de posición" numérico que dice: *"Aquí debería ir un número, pero no lo tenemos"*.

#### 2. El misterio del `None` en las Bases de Datos
¿Puede una base de datos venir con `None`? Sí y no.
* En la Base de Datos (SQL): Se llama `NULL`. Es un estado que indica que el valor es desconocido o no aplicable.
* Al importar a Python: El conector de la base de datos traduce ese `NULL` de SQL al `None` de Python.
* ¿es "grave"? `None` es un objeto de tipo `NoneType`.
No puedes sumar `5 + None` = ❌ (daría error) rompe la operación: `10 + None = Error`
Pero pandas lo convierte a NaN para evitar errores.
Pues sí puedes sumar `5 + NaN` (el resultado es `NaN`). Por eso Pandas prefiere convertir los `None` a `NaN`: para que el código no "explote" al hacer cálculos.


#### 3. ¿Por qué aparecen valores nulos en un dataset?
Los valores faltantes existen porque los datos del mundo real nunca están completos.
Causas comunes:
campo olvidado de llenar en un formulario
dato ilegible en un documento
usuario no quiso compartir edad
información protegida
Dato no aplicable como “segundo apellido” vacío
Error técnico como: sensor falló
fallo en transmisión de datos
scraping incompleto
Integración de múltiples fuentes
como: bases de datos con estructuras diferentes
campos inexistentes en una fuente
Los nulos no son errores necesariamente: a veces representan información desconocida.

JSON { "edad": null } → se convierte a: None por Python, si la columna es numérica.
Base de datos: NULL → Python recibe: None → pandas lo convierte a: NaN

df.describe()
✔ ignora automáticamente valores NaN
✔ calcula estadísticas con los valores válidos
[10, 20, NaN, 30] →  promedio = 20

NumPy puro falla ante el valor nan: 
5 + np.nan =  nan #Se propaga como “valor desconocido”.
NumPy puro falla por ejemplo a calcular el promedio: 
np.mean([10, 20, np.nan])
resultado: nan
Pero pandas:
pd.Series([10,20,np.nan]).mean()
resultado: 15
Pandas ignora NaN automáticamente.
pandas ignora NaN en Sumas:
10 + 20 + NaN = 30
NaN no cuenta como valor para CONTEOS:
count = 2

`""` (Vacío)(tipo: string) | Es una cadena de texto de longitud cero.
Pandas

Imagina que estás organizando una carrera de ciclismo:
0 → llegó en 0 segundos
NaN → corrió pero no sabemos el tiempo
None → nunca participó
"" → alguien escribió el nombre pero dejó el tiempo vacío


df.dropna()        # eliminar
df.fillna(0)       # reemplazar
df.fillna(df.mean())  # estimar